### ISSUE TITLE
Turn to a constrained user after the boot

### ISSUE THREAD

**Issue by mengxiang0811** [AltraMayor/gatekeeper#140]
In current implementation, we are assuming that the user who runs Gatekeeper/Grantor must be root to bootstrap, but can we turn to a constrained user after the boot? This is important because depending on which user we are using to run Gatekeeper/Grantor, we may need to change owner and access mode of the log file just created.

**Comment by AltraMayor** [comment]
This is also important because a limited user after the boot scopes how much bad stuff can be done if Gatekeeper/Grantor servers can ever be remotely compromised.

**Comment by cjdoucette** [comment]
One starting point for this: http://mails.dpdk.org/archives/users/2016-July/000720.html

**Comment by mengxiang0811** [comment]
According to the section 8.2 in [DPDK documentation](https://doc.dpdk.org/guides/linux_gsg/enable_func.html#running-dpdk-applications-without-root-privileges), it seems that we cannot change the DPDK required permissions since kernel version 4.0: ``the instructions below will allow running DPDK as non-root with older Linux kernel versions. However, since version 4.0, the kernel does not allow unprivileged processes to read the physical address information from the pagemaps file, making it impossible for those processes to use HW devices which require physical addresses``

**Comment by AltraMayor** [comment]
Qiaobin, the reference you quoted is saying that an unprivileged process cannot read the physical address information from the pagemaps file, so a non-root user cannot bootstrap Gatekeeper. But we can start Gatekeeper as root, read and initialize all we need and, then, downgrade the user. That's the solution advocated in the email that Cody quoted.

**Comment by mengxiang0811** [comment]
I see the difference. Does it mean that after initializing the mapping hugepages virtual to physical addresses, Gatekeeper will always read the virtual addresses instead of the physical addresses, so that it doesn't need privileged permissions?

**Comment by AltraMayor** [comment]
I may be wrong here, but my understanding is that DPDK only needs the physical address to set up a memory map. So after proper mapping, DPDK is just using virtual addresses.

Before sinking a lot effort into this issue, do the following test: downgrade the user (hardcode it to lower the effort) just before stage 3 of initialization begins. You'll need to set up Gatekeeper to process some packages to see if everything is working.

**Comment by AltraMayor** [comment]
We run Gatekeeper as root (in your example with `sudo`) and change it to a user (in your example `qiaobin`) specified in `struct net_config`. We should use `struct net_config` because it's a global parameter.

That tutorial is okay, but you may prefer to take a look at `drop_privileges()` in file `utils.c` of project [watchcatd](http://oss.digirati.com.br/watchcatd/). You can download the code [here](http://oss.digirati.com.br/watchcatd/watchcatd-1.3.1.tar.gz). Andre and I implemented `watchcatd` many years ago and the code is very well tested in production.

**Comment by mengxiang0811** [comment]
1. Error: ``GATEKEEPER DYN CFG: Failed to unlink(/tmp/dyn_cfg.socket) - (No such file or directory)``
The related code is: https://github.com/AltraMayor/gatekeeper/blob/master/config/dynamic.c#L278
Reason: permission issue when unlinking the socket.
``srwxr-xr-x 1 root root    0 Jan 30 04:22 dyn_cfg.socket``

2. Error: ``GATEKEEPER CPS: Can't open /proc/modules: No such file or directory``
The related code is: https://github.com/AltraMayor/gatekeeper/blob/master/cps/kni.c#L1019
https://github.com/AltraMayor/gatekeeper/blob/master/cps/kni.c#L1078
Reason: permission issue when removing the rte_kni
``-r--r--r-- 1 root root 0 Jan 30 04:51 /proc/modules``

3. Error: ``EAL: free_seg_walk(): Cannot open '/dev/hugepages': No such file or directory``
The related code is: https://github.com/cjdoucette/dpdk/blob/97b0ac77f5ae775d01e7f176853e3721cb2d8419/lib/librte_eal/linuxapp/eal/eal_memalloc.c#L1012
Reason: permission issue when opening the directory.
``drwxr-xr-x   3 root root           0 Jan 30 04:22 hugepages``

4. Error: ``EAL: Unable to open directory /var/run/dpdk/rte``
The related code is: https://github.com/cjdoucette/dpdk/blob/97b0ac77f5ae775d01e7f176853e3721cb2d8419/lib/librte_eal/common/eal_common_proc.c#L972
Reason: permission issue when opening the directory.
``drwx------ 2 root root 200 Jan 30 04:22 rte``

5. Error: ``EAL: Could not send sync request to secondary process``
The related code is: https://github.com/cjdoucette/dpdk/blob/97b0ac77f5ae775d01e7f176853e3721cb2d8419/lib/librte_eal/common/malloc_mp.c#L591
Reason: the failure in the above error 4.

Moreover, even using ``rte_exit()`` right after ``rte_eal_mp_wait_lcore();`` in ``main/main.c``, the errors are still there.

**Comment by AltraMayor** [comment]
Question 1: what is the implication after Gatekeeper finishes?

Question 2: what is the implication if Gatekeeper boots up again without the kernel is not rebooted?

**Comment by mengxiang0811** [comment]
For question 1:
1. the error message: ``GATEKEEPER DYN CFG: Failed to unlink(/tmp/dyn_cfg.socket) - (No such file or directory)`` implies that Gatekeeper fails to unlink the socket used by the Dynamic Configuration block.

2. the error message: ``GATEKEEPER CPS: Can't open /proc/modules: No such file or directory`` implies that Gatekeeper fails to remove the kernel module ``rte_kni.ko``.

3. the error message: ``EAL: free_seg_walk(): Cannot open '/dev/hugepages': No such file or directory``. After checking the code, once this error happens, DPDK cannot call the [``free_seg()``](https://github.com/cjdoucette/dpdk/blob/97b0ac77f5ae775d01e7f176853e3721cb2d8419/lib/librte_eal/linuxapp/eal/eal_memalloc.c#L1029) function to free (i.e., unmap) the segment.

4. the last two error messages are from the same issue. Since the error message comes from the function call ``request_sync()``, which further calls ``rte_mp_request_sync()``. This error message relates to the [DPDK Multi-process Support](https://doc.dpdk.org/guides/prog_guide/multi_proc_support.html), i.e., primary process and secondary process. In case of Gatekeeper, it's a standalone DPDK process, so it's a primary processes. Thus, Gatekeeper process needs to [broadcast message to all secondaries](https://github.com/cjdoucette/dpdk/blob/97b0ac77f5ae775d01e7f176853e3721cb2d8419/lib/librte_eal/common/eal_common_proc.c#L969), in which it needs to open the directory containing the multi-process socket. However, as a downgraded user, it cannot access the socket. Therefore, the primary process fails to notify of changes in memory map.

For question 2:
1. the error won't affect if Gatekeeper boots up again, this is because Gatekeeper will try to unlink any old socket, and then create a new one.

2. Previously, we don't check the kernel module files, so one has to manually remove the kernel module first. In the current version, this won't affect the result as well due to Cody's latest closed [pull request](https://github.com/AltraMayor/gatekeeper/pull/181).

3. Indeed, I have tried to reboot Gatekeeper several times, each time I checked the usage of hugepages, it seems that the usage are always keeping the same no matter how many times I reboot Gatekeeper. This may need further investigation. Moreover, one concern is that the primary process after downgrading the user cannot make any changes to the memory map. Is it possible to have such operations after the user downgrade?

4. Since Gatekeeper is a standalone process, I guess it won't affect much about the synchronous requests. However, if Gatekeeper needs to support multiple processes (i.e., primary process and secondary processes) in the future, the secondary processes and the primary process won't have consistent view of the memory mapping, then there is a problem.

**Comment by cjdoucette** [comment]
A few more things to check, which are concerned with the KNI and may require privileged operations:

- When Gatekeeper closes, do the KNIs (`kni_front` and `kni_back` interfaces) get removed?
- Setting the MTU of the KNI. While Gatekeeper is running, if a user performs a command like `sudo ip link set mtu 1499 dev kni_front` to change the MTU of one of the KNIs, the request goes through Gatekeeper [here](https://github.com/AltraMayor/gatekeeper/blob/master/cps/kni.c#L69-L78) and I believe we change both the MTU of the KNI and of the relevant Gatekeeper interface. We need to make sure that both of these changes either succeed or fail, and not have one MTU changed while the other fails. We may need to disable the ability to change the MTU as we did in the function `kni_disable_change_mac_address()`. 
- We should do a similar kind of check with `kni_change_if()`. I think it gets called when the KNI is created, but we may want to disable the ability to change it after Gatekeeper boots, or at least make sure either both the KNI and Gatekeeper interface succeed or fail in being brought up/down when this function is called.

**Comment by mengxiang0811** [comment]
Hi @cjdoucette ,

Thanks for bringing the comments:

- Yes, when Gatekeeper closes, the KNIs did get removed.

- When performing command ``sudo ip link set mtu 1499 dev kni_front``, it changed the MTU of the front KNI successfully. However, the back KNI's MTU won't change. After performing command ``sudo ip link set mtu 1499 dev kni_back``, we can change the back KNI's MTU as well. It seems that we cannot check the MTU of the Gatekeeper interfaces through command ``ifconfig``, as they are bound to DPDK then.

- After checking the code, it seems that [kni_change_if()](https://github.com/AltraMayor/gatekeeper/blob/3647526057bbb60d789781d94ccf84098c1d3ee0/cps/main.c#L707) only gets called when the KNI is created. I wonder is there a way to change the KNI or Gatekeeper interface after it boots up? Or whether the change is necessary?

**Comment by cjdoucette** [comment]
The KNIs are linked to actual interfaces, so when we try to change the MTU or the link status of the KNI it also affects the Gatekeeper interface.

For example, when we change the MTU of the KNI it should change the MTU of the Gatekeeper server too. I understand that when Gatekeeper is running under a constrained user, the command to change the MTU of the KNI succeeds. Could you add this code to the end of `kni_change_mtu()` to see if it changes the Gatekeeper MTU as well?

```
-       return rte_eth_dev_set_mtu(port_id, new_mtu);
+       int ret = rte_eth_dev_set_mtu(port_id, new_mtu);                        
+       uint16_t mtu;                                                           
+       rte_eth_dev_get_mtu(port_id, &mtu);                                     
+       printf("new MTU: %hu\n", mtu);                                          
+       return ret;
```

We can bring the KNI up and down using a similar command: `sudo ip link set kni_front down`, which I believe may also bring the Gatekeeper interface down. My two questions are: even when Gatekeeper is running as a constrained user, does this command succeed in changing both the link status of the KNI and the Gatekeeper interface?

And second, do we even want to allow changes to the MTU and link status of Gatekeeper interfaces in this way?

**Comment by mengxiang0811** [comment]
Thanks @cjdoucette !

- With the code change as you suggested above, yes, it changes the Gatekeeper MTU as well.

- With the command to bring the KNI up and down, there are some error messages:
``RTNETLINK answers: Input/output error`` when trying to bring the KNI down and then up.

The detailed output in the Gatekeeper log when trying to bring down and up the front KNI is as follows:
```GATEKEEPER CPS: cps update: [DEL] family=10 dst_len=48 src_len=0 tos=0 table=254 protocol=2 scope=2 type=0 flags=10
GATEKEEPER CPS: cps update: dst: 2001:db8:1::
GATEKEEPER CPS: cps update: oif=135
GATEKEEPER CPS: cps update: the rtnetlink command has information (RTA_PRIORITY with prio=256) that we don't need or don't honor
GATEKEEPER CPS: cps update: [DEL] family=10 dst_len=8 src_len=0 tos=0 table=255 protocol=3 scope=3 type=0 flags=10
GATEKEEPER CPS: cps update: dst: ff00::
GATEKEEPER CPS: cps update: oif=135
GATEKEEPER CPS: cps update: the rtnetlink command has information (RTA_PRIORITY with prio=256) that we don't need or don't honor
GATEKEEPER GK: del_fib_entry_locked received a request to delete FIB entry 2001:db8:1::/48 with prefix action 3; Gatekeeper may need to restart
GATEKEEPER GK: Delete an non-existent IP prefix (ff00::/8)
Device with port_id=3 already stopped
ixgbe_alloc_rx_queue_mbufs(): RX mbuf alloc failed queue_id=1
ixgbe_dev_rx_queue_start(): Could not alloc mbuf for queue:1
ixgbe_dev_start(): Unable to start rxtx queues
ixgbe_dev_start(): failure in ixgbe_dev_start(): -1
GATEKEEPER CPS: kni_change_if: Failed to start port 3
```
The same thing happens without turning to a constrained user after boot, so I guess this error message relates to the way to change the KNI status.

**Comment by cjdoucette** [comment]
Thanks for checking this Qiaobin! I think this means that turning to a constrained user does not affect the KNI and its operations.

**Comment by mengxiang0811** [comment]
By changing the permissions of the directories ``/var/run/dpdk`` and ``/var/run/dpdk/rte``, the Gatekeeper successfully removes the error messages 3, 4 and 5.

The commands used to change the permissions are:
```
sudo chmod o+x /var/run/dpdk
sudo chmod o+r /var/run/dpdk/rte
```

**Comment by cjdoucette** [comment]
Does it make sense to do the same for `/tmp/dyn_cfg.socket`?

**Comment by mengxiang0811** [comment]
Even changing the permission for ``/tmp/dyn_cfg.socket``, Gatekeeper still couldn't remove the file.

```
qiaobin@xia1:~$ ls -l /tmp/dyn_cfg.socket 
srwxr-xr-x 1 root root 0 Feb 15 21:00 /tmp/dyn_cfg.socket
qiaobin@xia1:~$ sudo chmod o+w /tmp/dyn_cfg.socket 
qiaobin@xia1:~$ ls -l /tmp/dyn_cfg.socket 
srwxr-xrwx 1 root root 0 Feb 15 21:00 /tmp/dyn_cfg.socket
```

I am trying to find the materials about removing a socket file without privileges, however, I didn't get much useful information on this.

**Comment by mengxiang0811** [comment]
Is it possible because of the permissions of ``/tmp`` (i.e., ``drwxrwxrwt``)? The type ``t`` means that only the owner of a file can remove it, so that any files under this directory can only be removed by ``root``?

**Comment by mengxiang0811** [comment]
For the ``/tmp`` directory, its permissions are ``drwxrwxrwt ``, where the sticky bit is set. According to the Wikipedia article: [Sticky bit](https://en.wikipedia.org/wiki/Sticky_bit), we know that ``when a directory's sticky bit is set, the filesystem treats the files in such directories in a special way so only the file's owner, the directory's owner, or root can rename or delete the file. `` Thus, as a normal user, it doesn't have the permission to delete the socket file. Should we change the socket file to another directory?

**Comment by AltraMayor** [comment]
About the socket, network operators are likely to put it in a folder under `/var/run` in production, for example `/var/run/gatekeeper`. Therefore, folder `/var/run/gatekeeper` can have proper permissions to enable Gatekeeper to remove the socket under a constrained user.

Write up a wiki page summarizing all the knowledge we gathered in this page. Digirati can test the content of this wiki page and give feedback to improve it.

**Comment by mengxiang0811** [comment]
By putting the socket file (i.e., ``dyn_cfg.socket``) under ``/var/run/`` folder, one cannot remove the socket file even we change the owner of the socket file. The reason is that ``/var/run`` is a symbolic link to ``/run`` folder, even though the link has permission ``777`` (``lrwxrwxrwx  1 root root      4 Jul 25  2018 run -> /run``), the ``/run`` folder has default permission ``drwxr-xr-x  28 root root       1080 Feb 23 08:05 run``. That is to say, only the ``root`` has permission to ``create/delete/change`` the files under ``/run``. I wonder should we change the permission of ``/run`` or put the socket file into a different folder? Any thoughts? @AltraMayor

**Comment by AltraMayor** [comment]
`/var/run/gatekeeper` itself is a folder not a file, so it can have the rights we need. The socket file goes inside this folder. The new folder will be created during the installation of Gatekeeper.
