### ISSUE TITLE
Map queue ID to GK instance more efficiently

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#150]
When looking up the GK block responsible for a given flow in `get_responsible_gk_mailbox()`, we loop over the queue IDs of each GK instance to match the queue ID that corresponds to the flow. Instead, we should have a mapping of queue ID -> GK instance so that we can get the GK instance without a loop.

**Comment by AltraMayor** [comment]
Isn't the `queue_id` a small integer? If so, a small array is a much simpler solution.

**Comment by Hrish1** [comment]
Is 32,768 the maximum value a queue ID can take? So should that be the length of the array?

**Comment by AltraMayor** [comment]
A dynamicly allocated array would avoid a lot of the wasted memory of a size-fixed array since no host should have more than 1000 queues; the typical number should be even less than 100.

**Comment by Hrish1** [comment]
We can start with a small array size(say 8) and we double the size in case we have more queues,(Table doubling approach)

**Comment by Hrish1** [comment]
In `get_queue_id` function the upper-bound on the `queue_id` seems to be `QUEUE_TYPE_MAX` . How about having the array as big as `QUEUE_TYPE_MAX+1`? In the `gk_stage1` function we can fill this array(queue_id to instance) and use these entries in `get_responsible_gk_mailbox()` .

**Comment by AltraMayor** [comment]
The number of receiving queues is available at `iface->num_rx_queues` and the number of transmitting queues at `iface->num_tx_queues`. The constant `QUEUE_TYPE_MAX` represents the types of queues, not the number of queues.
