### ISSUE TITLE
Find minimum set of needed RSS hash functions

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#152]
Gatekeeper does not seem to require all protocols listed in `ETH_RSS_IP`. We should find the minimum set of hash functions needed to use Gatekeeper and replace `ETH_RSS_IP` with the logical and of them.

More information here: https://github.com/AltraMayor/gatekeeper/pull/103#discussion_r216733202

**Comment by mengxiang0811** [comment]
After reviewing all the DPDK drivers, it seems that there is no one hash function in ``ETH_RSS_IP`` that is supported by all drivers. For example:

The ``i40e`` driver contains the following hash functions:

    #define I40E_RSS_OFFLOAD_ALL ( \
        ETH_RSS_FRAG_IPV4 | \
        ETH_RSS_NONFRAG_IPV4_TCP | \
        ETH_RSS_NONFRAG_IPV4_UDP | \
        ETH_RSS_NONFRAG_IPV4_SCTP | \
        ETH_RSS_NONFRAG_IPV4_OTHER | \
        ETH_RSS_FRAG_IPV6 | \
        ETH_RSS_NONFRAG_IPV6_TCP | \
        ETH_RSS_NONFRAG_IPV6_UDP | \
        ETH_RSS_NONFRAG_IPV6_SCTP | \
        ETH_RSS_NONFRAG_IPV6_OTHER | \
        ETH_RSS_L2_PAYLOAD)

while the ``ixgbe`` driver indicates that it supports these hash functions:

    #define IXGBE_RSS_OFFLOAD_ALL ( \
        ETH_RSS_IPV4 | \
        ETH_RSS_NONFRAG_IPV4_TCP | \
        ETH_RSS_NONFRAG_IPV4_UDP | \
        ETH_RSS_IPV6 | \ 
        ETH_RSS_NONFRAG_IPV6_TCP | \
        ETH_RSS_NONFRAG_IPV6_UDP | \
        ETH_RSS_IPV6_EX | \
        ETH_RSS_IPV6_TCP_EX | \
        ETH_RSS_IPV6_UDP_EX)

There is no overlap in the two drivers in terms of the hash functions in ``ETH_RSS_IP``.

**Comment by cjdoucette** [comment]
I actually have been running some tests and I have found that `ETH_RSS_IPV4|ETH_RSS_IPV6` seem to cover IPv4 and IPv6 packets for UDP, TCP, and ICMP (IPv4) and for fragmented packets for both IPv4 and IPv6. I think the only thing left to test is to make sure these work for IPv6 extension headers.

**Comment by cjdoucette** [comment]
And I was able to make ICMPv6 packets be received by different lcores configured for RSS as well, indicating that `ETH_RSS_IPV4|ETH_RSS_IPV6` seems to be enough for any IPv4 and IPv6 packet, which is what we want.

@AltraMayor Any other tests you can think of? Or is it safe to replace `ETH_RSS_IP` with `ETH_RSS_IPV4|ETH_RSS_IPV6`?

**Comment by mengxiang0811** [comment]
As stated in the Intel 82599 datasheet, for IP packets without considering the layer4 information, DPDK will concatenate ``SourceAddress`` and ``DestinationAddress`` into one single byte-array to calculate the RSS hash values. For example, for IPv4 hash functions, the input is ``Input[8] = @12-15, @16-19``, while the input for IPv6 hash function is ``Input[32] = @8-23, @24-39``. For IPv6, ``the IPv6 extended header fields are not taken into account for the queue classification by RSS filter``. So, the extension headers and the layers above the IP layer may not affect the hash value calculation.

Moreover, as the GT blocks will receive IP-in-IP packets, the Intel 82599 datasheet also states: ``tunneled IP to IP packets are considered for the RSS functionality as IP packets. The RSS logic ignores the L4 header while using the outer (first) IP header for the RSS hash.`` So, I think we are safe to process the tunneled packets in GT blocks.

A question is: what's the difference among the hash functions in ``ETH_RSS_IP`` for IPv4 and IPv6 separately? I didn't find any materials about their difference, I guess the functions are hardcoded in the hardware NIC? If ``ETH_RSS_IPV4`` and ``ETH_RSS_FRAG_IPV4`` have the same logic except for the packet type when applying them, then ``ETH_RSS_IPV4`` could be enough.

**Comment by cjdoucette** [comment]
I think it's possible that some NICs may support the ability to recognize fragmented packets and only apply an RSS hash to those packets (instead of all IP packets), in which case the application would use `ETH_RSS_FRAG_IPV{4,6}`. Since we want to apply the RSS hash to all IP packets, I don't think we need it.

**Comment by cjdoucette** [comment]
This is off-topic, but is related to the n-tuple filters that we use. On page 292 of the 82599 datasheet, it says:

• Packets with tunneling (any combination of IPv4 and IPv6) miss the 5-tuple filters.
• Fragmented packets miss the 5-tuple filters.

This means that, for example, BGP packets received by Gatekeeper servers would miss the n-tuple filter that is supposed to direct it to the CPS block, and it would be hashed by RSS to a GK block. Since n-tuple filters in general are available, the IPv4 ACL will not be activated on startup, and the BGP packet would be treated as a normal data packet by GK.

This means that we always need to have the IPv4 ACL turned on (even when there is support for n-tuple filter in the NIC) in order to catch fragmented packets.
