### ISSUE TITLE
What other transport protocols should we support?

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#157]
The simple policy in lua/policy.lua supports TCP and UDP. What other protocols do we need to support in production?

Even if it is not implemented in `lookup_simple_policy()`, we should have an answer to this question for production purposes.

**Comment by cjdoucette** [comment]
Hi @mengxiang0811,

I noticed you self-assigned this issue -- I started some work on it but forgot to assign the issue to myself. If it helps, here's what I came up with:

https://github.com/cjdoucette/gatekeeper/commit/a9a52a15d3851408014c7a6e75dc2d099ed0a0e3

It's not necessarily complete and will probably need to be rebased but that's the idea I had.

**Comment by cjdoucette** [comment]
In fact, it is definitely not complete because I have it returning an undefined `declined` policy decision, but that could be added.

**Comment by mengxiang0811** [comment]
Thanks a lot @cjdoucette ! Your work helps a lot! I also added the example of ICMPV6 packets.
