### ISSUE TITLE
Implement a tool to send GGU flush requests out

### ISSUE THREAD

**Issue by mengxiang0811** [AltraMayor/gatekeeper#171]
In #90 , we are creating a new packet format for flush requests instead of implementing a flush request as part of policy decisions because a flush request does not align well with a policy decision.

These flush requests will be rare and always generated by the explicit request of network operators to deal with some impactful change. We should have a tool named ``gkadm`` to send these requests out. The very first version of ``gkadm`` should just receive all its parameters from the command line and send out the packet. Thus, gkadm doesn't need a list of prefixes for now.

**Comment by AltraMayor** [comment]
As concluded at https://github.com/AltraMayor/gatekeeper/pull/90#discussion_r246378099 , we are giving up on the GGU extension and implementing the flush of flows at the dynamic configuration block. Thus, this issue is no longer relevant.
