### ISSUE TITLE
An issue on running the example dynamic configuration request

### ISSUE THREAD

**Issue by mengxiang0811** [AltraMayor/gatekeeper#173]
In the latest version of Gatekeeper, when trying to dynamically configure Gatekeeper server via the client, there will be an error message: ``recievd: gk: failed to add an FIB entry``, which means it failed to add the FIB entries.

**Comment by cjdoucette** [comment]
I think this has something to do with the FIB entry gateway addresses needing to be in the same network as the Gatekeeper IP addresses. We changed both the IP addresses of Gatekeeper in lua/net.lua and in the example dynamic request a couple of weeks ago.

I'll look into why this is happening and come up with a fix.
