### ISSUE TITLE
Accounting for NUMA sockets in calculate_net_config_para()

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#185]
`calculate_net_config_para()`, which was added in pull request #179, will likely overestimate the critical parameter `net_conf->gatekeeper_num_mbuf` and apply it to all NUMA sockets where there's more than one NUMA socket. This issue will only become relevant once Gatekeeper and Grantor servers need to use more than one NUMA socket, what's not a reality in production yet.

A possible solution:
1. After `config_gatekeeper()` in `main()` returns, call `launch_at_stage1()` to launch a new step called `alloc_pktmbuf_pools()` that will be launch at the very end of stage 1 and allocate all the pools.
2. `lib/net.c:get_queue_id()` will do the bookkeeping that `calculate_net_config_para()` needs, but it won't configure the requested queue; it'd be impossible since the pools are not available then. Instead, `get_queue_id()` will push another step into stage 1 to configure the requested queue. Notice that not only is this new step added while stage 1 is being executed, but it also added after `alloc_pktmbuf_pools()`, so the pools will be available then.
3. Update `calculate_net_config_para()` to account for NUMA sockets in `alloc_pktmbuf_pools()`.

**Comment by AltraMayor** [comment]
Two notes on the proposed solution:
1. The solution will enable us to discard `net_launch_at_stage1()` since the only purpose of `net_launch_at_stage1()` is to calculate `iface->num_rx_queues` and `iface->num_tx_queues` before calling `rte_eth_dev_configure()` in `lib/net.c:init_port()`. `rte_eth_dev_configure()` is the only function that uses `iface->num_rx_queues` and `iface->num_tx_queues`. `get_queue_id()` can obtain those parameters and `init_port()` can run in `alloc_pktmbuf_pools()`. After this change `alloc_pktmbuf_pools()` would be named as `start_net_before_stage2()`.

2. Parameter `net_conf->gatekeeper_num_mbuf` will become an array indexed by the NUMA socket.

**Comment by AltraMayor** [comment]
In large deployments, there will be a need to have multiple SOL blocks due to (1) the number of GK blocks and packet rate being too high for a single SOL block to handle, and (2) the need to have GK blocks associated to each socket for faster memory accesses. Therefore, accounting for NUMA sockets is essential for large deployments.

**Comment by AltraMayor** [comment]
Doesn't pull request #377 solve this issue?

**Comment by mengxiang0811** [comment]
Agreed! The pull request #377 does solve this issue by creating a mempool for each block. The solution is NUMA-aware. One thing left is to enable multiple SOL blocks for large deployments.

**Comment by AltraMayor** [comment]
Pull request #390 closed this issue.
