### ISSUE TITLE
Limit rate of log entries

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#19]
Gatekeeper writes log entries to report general information, warnings, and diagnosis information. These log entries are essential for operating a Gatekeeper deployment. However, during high loads or DDoS attacks, there is a potential for the log subsystem to become too heavy of a burden and impact the capacity of Gatekeeper servers. Especially, if attackers find an easy way to trigger log entries. To dodge this risk entirely, Gatekeeper must rate limit the log entries.

The Linux kernel has already a solution for this issue, namely functions: net_err_ratelimited(), net_warn_ratelimited(), net_notice_ratelimited(), among others. The proposed solution here is to study these functions to verify if we can/should adopt them in Gatekeeper. If not, we'll need to devise our own solution for this problem.

**Comment by cjdoucette** [comment]
As part of this issue, I think we should consider the `XXX` tag in `main/main.c`:

    /* XXX Set the global log level. Change it as needed. */
    rte_set_log_level(RTE_LOG_DEBUG);

**Comment by mengxiang0811** [comment]
Good point! After checking the DPDK source code for log, indeed I didn't find the code related to this feature. Most of the functions for log are implemented in file ``lib/librte_eal/common/eal_common_log.c``.

**Comment by AltraMayor** [comment]
Thank you for checking that.
