### ISSUE TITLE
Find kernel module path automatically

### ISSUE THREAD

**Issue by andrenth** [AltraMayor/gatekeeper#211]
Currently Gatekeer requires the path to the `rte_kni` kernel module to be specified in `cps.lua` by setting the `kni_kmod_path` variable. This could be automated by replicating the behavior of the `modinfo` command:

```sh
$ modinfo -Ffilename rte_kni
/lib/modules/4.15.0-45-generic/updates/dkms/rte_kni.ko
```

To do that, `modinfo` links to the `libkmod` library and calls `kmod_module_get_path()`, so Gatekeeper could do the same.

**Comment by cjdoucette** [comment]
Is `/lib/modules/4.15.0-45-generic/updates/dkms/rte_kni.ko` the .ko file of the currently loaded (or maybe more recently loaded) version of this kernel module? When we recompile DPDK to update it or simply want to point to a particular version of the kernel module, I wonder if we need the ability to specify a particular .ko file in the configuration.

**Comment by AltraMayor** [comment]
`/lib/modules/4.15.0-45-generic/updates/dkms/rte_kni.ko` is the installed KNI kernel module for the running kernel. It may or may not be loaded into the kernel.

I think having a way to specify a specific .ko file would be helpful for development. For example, one will want to specify the file `rte_kni.ko` while working to port Gatekeeper to a newer DPDK or patching the file `rte_kni.ko` itself. However, automatically finding the installed KNI kernel module for the running kernel is the way to go for production.

**Comment by AltraMayor** [comment]
This issue is very helpful in production since the path will change with each update of the kernel. So I'm moving it to the First Milestone milestone.

Whenever the parameter `kni_kmod_path` of `staticlib.c.run_cps()` is `NULL`, Gatekeeper must look up the path using `libkmod`.
