### ISSUE TITLE
Fine tune support for BIRD

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#223]
There are some ways we can improve Gatekeeper's reporting of network information to better interface with BIRD, including:

- Exclude the attribute `RTA_GATEWAY` when reporting neighbor routes.
- Respond with an empty list when the daemon asks for `AF_MPLS` routes.
- Report `GK_DROP` routes to BIRD using `RTN_BLACKHOLE` entries.

**Comment by AltraMayor** [comment]
In the case of `RTN_BLACKHOLE`, let's also support to add/delete this kind of route coming from BIRD as `RTM_NEWROUTE` and `RTM_DELROUTE`. We need to add the following `struct` to the `union u` in `struct gk_fib` to be able to report when a GK_DROP was added from the Dynamic Configuration (i.e. `RTPROT_STATIC`) and from BIRD (i.e. `RTPROT_BIRD`):
```
struct {
	uint8_t rt_proto;
} drop;
```
