### ISSUE TITLE
Forwarding granted packets directly to their destinations

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#230]
When a flow is moved to the granted channel, Grantors servers just decapsulate its packets and send them to their destinations. Instead, Gatekeeper servers could simply forward the packets in the granted channel without encapsulation to their destinations. This would reduce bandwidth consumption since there would be no encapsulation header and reduce the load at Grantor servers.

The only drawback of this solution is that Grantor servers would no longer be able to build a global view of the traffic to enhance policy decisions. This trade-off could be managed by allowing policy decisions to discriminate which flows go directly to their destinations and which flows keep crossing Grantor servers.

**Comment by cjdoucette** [comment]
I believe we already have a manual way of doing this with forwarding actions `GK_FWD_GATEWAY_BACK_NET` and `GK_FWD_NEIGHBOR_BACK_NET` using the dynamic configuration.

Is there something more that this task would need to be completed? Perhaps to allow either Gatekeeper or Grantor to detect that bandwidth usage is too high or Grantor cannot keep up with requests, and trigger this mode?

**Comment by cjdoucette** [comment]
Actually, I realize now that just using those forwarding actions wouldn't be equivalent. The actual forwarding might be the same, but those actions skip the Gatekeeper request/rate limiting algorithm that governs whether the forwarding should even happen, and how.

**Comment by AltraMayor** [comment]
If we add controls to a granted flow such that a policy decision can determine (1) if a granted flow encapsulates or not, and, if it encapsulates, (2) the destination of the packets (i.e. the destination address of the outer header), we accomplish two things:
1. Item (1) allows for Grantor servers to reduce their load when needed or possible.
2. Item (2) enables Gatekeeper servers to act as load balancers.

While item (1) was the motivation for this issue, item (2) opens the door to increase the value of Gatekeeper for network operators because not only would a Gatekeeper deployment address DDoS attacks, but it would also eliminate the need for dedicated load balancers. Moreover, since policies will determine the destination of encapsulated packets of granted flows, these policies can (a) implement any desirable hash function and load balancing mechanism as well as (2) balance load between geographically distributed destinations.

When Gatekeeper acts as a load balancer, the final destinations have to decapsulate the packets themselves. This can be done with a simple BPF program using [XDP](https://www.iovisor.org/technology/xdp) like [Katran](https://code.fb.com/open-source/open-sourcing-katran-a-scalable-network-load-balancer/) does. This way, the decapsulation adds a small overhead to final destinations.

**Comment by AltraMayor** [comment]
Enabling policies to define the destination of encapsulated packets works as a form of flow redirection. This feature alone opens Gatekeeper to many new possibilities: direct delivery of granted packets to destinations, load balancing, path control, and integrating with intrusion detection systems such as [Suricata](https://suricata-ids.org/), [Snort](https://www.snort.org/), and [Zeek (formerly Bro)](https://www.zeek.org/).

Combined with the fact that policies control when flow redirection is applied, to which flows, and to where redirecting them, flow redirection has the potential to become a feature as valuable as DDoS protection.

**Comment by AltraMayor** [comment]
The following idea might be too wild, but it was inspired by our meeting yesterday, Monday, April 29th, 2019.

Instead of adding flags to describe how a granted state in the flow table deals with its flow as we've been discussing above, a policy could send an eBPF program to decide what the Gatekeeper server will do with the packets of the flow.

The latest DPDK already has experimental support to eBPF as one can see [here](https://doc.dpdk.org/api/rte__bpf_8h.html) and [here](https://doc.dpdk.org/guides/prog_guide/bpf_lib.html). A 9-slide presentation deck of Konstantin Ananyev, the DPDK developer doing this work, is available [here](https://www.dpdk.org/wp-content/uploads/sites/35/2018/10/pm-07-DPDK-BPFu6.pdf). This presentation gives an overview of the work. The page [Dive into BPF: a list of reading material](https://qmonnet.github.io/whirl-offload/2016/09/01/dive-into-bpf/) is an excellent entry point to learn more about BFP.

**Comment by AltraMayor** [comment]
This issue grew into a lot of big ideas and we need to break it down into multiple issues to incrementally implement the ideas here.

The idea of associating a BPF program to a flow state is implemented in the pull request #295. Issue #297 was created to house the idea of adding load balancing to Gatekeeper, and issue #298 to house the idea of flow redirection.

Thus, all one has to implement to close this issue is to add the parameter `int direct_if_possible` to `gk_bpf_encapsulate()`. When this parameter is `true` and the parameter `priority` is `PRIORITY_GRANTED`, the packet is not encapsulated, its IP header updated with `priority`, and sent out. Notice that the destination MAC address to be used is the same that would be used if the packet were to be encapsulated; this assumption simplifies the code since the GK blocks and the LLS block don't need to track neighbors in the back network. This assumption is not always true when Gatekeeper servers are used as load balancers, but we are pushing the effort to weak this assumption to issue #297.

**Comment by AltraMayor** [comment]
In order for being able to work on this issue while pull request #295 is being reviewed, one can fork a branch from the branch `bpf` of the repository. Once that pull request is merged, rebasing to branch `master` will make the working branch ready for review.
