### ISSUE TITLE
Create a complex appliance on Chameleon for Gatekeeper test

### ISSUE THREAD

**Issue by mengxiang0811** [AltraMayor/gatekeeper#244]
To test Gatekeeper at scale, we may need to reserve tens of nodes in Chameleon testbed. Configuring each node manually is inefficient, and it's easier to create a [complex appliance](https://chameleoncloud.readthedocs.io/en/latest/technical/complex.html?highlight=yaml#sharing-complex-appliances) by writing a Heat Orchestration Template, which is a YAML file that specifies how resources are used and configured in a Complex Appliance. This also improves the repeatability and reproducibility of Gatekeeper tests, and can be potentially applied to other cloud providers powered by OpenStack.

**Comment by cjdoucette** [comment]
I’m currently working on the Heat Orchestration files for Gatekeeper.

One thing that you can look into if you have a chance is the scripts that each client will run.

- What dependencies and software will they need for generating packets?
- What are the command line options for the software we use to generate packets to control things like the rate and packet size?
- Should there be more than one packer generator running on each instance at once?

One other thing to consider: should we be reserving many instances with 1 Gb connections for clients, or should we reserve only a small number of instances with 10 Gb connections and run multiple packet generators? For example, we might be able to achieve our test with just four reserved instances if each instance has two 10 Gb interfaces:

- one instance on which we run multiple clients, altogether with the capacity to generate up to 20 Gb of traffic
- one instance for Gatekeeper, with a 10 Gb front interface and 10 Gb back interface
- one instance for Grantor, with a 10 Gb front interface
- one instance on which we run multiple target destinations for the clients

I think this setup would make it easiest to reserve instances within a single rack.

**Comment by cjdoucette** [comment]
Once we have the (1) complex appliance setup and (2) client and server tasks, then we can work on configuring the Gatekeeper FIB and policies to match the kind of tests we want to run.

**Comment by AltraMayor** [comment]
Cody's suggestion of having a small test environment, only four nodes, is good not only because it makes it easier to deal with the possible issues that we're going to find in this early stage of the tests, but it also helps others to try Gatekeeper with a small footprint.

Once the first tests are successful, we'll need to grow this small test environment to include a second Gatekeeper server and a Linux router to combine the traffic coming from both Gatekeeper servers in order for us to test the merge of channels: request, granted, legacy.

**Comment by cjdoucette** [comment]
In addition to the issue I found with baremetal instances not having multiple interfaces available, I found this restriction:

> In its default configuration, the bare metal deployment system used by Chameleon (OpenStack Ironic) is restricted to using a single shared network per site. The network configuration features available in the dashboard are not supported (Networks and Routers). On CHI@UC, network layer 2 isolation is optionally available for compute nodes. You may find more details on the documentation for Networking.

https://chameleoncloud.readthedocs.io/en/latest/technical/baremetal.html#customizing-networking

I think this is OK, it just means that for tests where we want to have a router in front of or behind a Gatekeeper server, we will need to use an instance.

**Comment by AltraMayor** [comment]
I'm closing this issue since we'll no longer support Chameleon.
