### ISSUE TITLE
GK block does not check IP support before lookup

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#259]
After receiving a burst of packets on both the front and back interface, the GK block extracts the packet information fully and performs a FIB lookup without checking whether it supports the IP type of the packet.

**Comment by Hrish1** [comment]
If by IP types you mean the IP versions, I guess a similar check is made in the `extract_packet_info()` function. It flags the non-IPv4/6 packets which are eventually dropped before any lookup.

**Comment by cjdoucette** [comment]
This issue has more to do with the fact that a Gatekeeper interface can be configured to run IPv4 only, by configuring `front_ips` to only have an IPv4 address in `lua/net.lua`. However, even in this case, the GK block will receive IPv6 packets and perform lookups on them, but they should just be dropped.

**Comment by Hrish1** [comment]
Before extracting packet info we could use the macro `RTE_ETH_IS_IPV4_HDR ` on `rte_mbuf *pkt`, after that  `ipv4_configured(gk_conf->net)` determines whether we drop the packet or not.

**Comment by AltraMayor** [comment]
I think that Cody is not suggesting to change the function that parses the packets, but just to decide on droping a packet or not based on Gatekeeper being configured to that version of IP.

**Comment by cjdoucette** [comment]
Yes, that's correct. Although Hrishav makes a good point by referencing the macro `RTE_ETH_IS_IPV4_HDR`, which checks what the hardware assigned the DPDK buffer's packet type(s) to be. In general we are not making use of the packet type library of DPDK but could be used in places for speedups, i.e. when we need to drop a packet without parsing its contents at all.

**Comment by cjdoucette** [comment]
1. Yes, that's right. We already have the code to check the IP version when we extract the packet info, we're just missing a check of whether Gatekeeper supports that IP version. So we should check that and make a drop in that case (before the lookup happens).

2. Yes, that's correct.
