### ISSUE TITLE
The CPS block must support editing the routing table of the GK blocks

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#27]
The BGP speakers that use the KNI interfaces exported by the CPS block must have a way to edit the routing table of the GK blocks, so Gatekeeper servers can send the outgoing traffic to the IX.

The editing of the routing table in the Linux kernel is usually done through the Netlink interface. If the CPS can support Netlink, it would be easier to patch BGP speakers to redirect the editing commands to Gatekeeper.

The BGP speaker Bird (http://bird.network.cz/) is a strong candidate to be patched given its popularity. Another positive factor is that they have documentation for developers:

http://bird.network.cz/?get_doc&f=prog.html

**Comment by AltraMayor** [comment]
This issue depends on pull request #42, which will soon be merged.

**Comment by AltraMayor** [comment]
Pull request #45, which adds functions `add_fib_entry()` and `del_fib_entry()` to edit GK's routing table, is one more step toward the completion of this issue.

**Comment by cjdoucette** [comment]
When complete, this feature should remove multiple `TODO` entries in `cps/kni.c`.

**Comment by AltraMayor** [comment]
Pull request #80 completed this issue.
