### ISSUE TITLE
Network configuration fails when using ENA

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#283]
Since the ENA driver does not support `rss_hash_conf_get()`, the call in the network configuration returns `-ENOTSUP`:

https://github.com/AltraMayor/gatekeeper/blob/master/lib/net.c#L1384

This causes the network configuration to exit since an error is returned.

**Comment by mengxiang0811** [comment]
After investigating the possible ways to obtain the RSS hash key, seems that ``rss_hash_conf_get`` is the only available interface. For ``struct rte_eth_dev_info``, it only contains some contextual information, e.g., hash key size, so we cannot use it here.
