### ISSUE TITLE
Deprecate function calls for Ethernet filter

### ISSUE THREAD

**Issue by mengxiang0811** [AltraMayor/gatekeeper#294]
In the latest DPDK, two function calls (i.e., ``rte_eth_dev_filter_supported()`` and ``rte_eth_dev_filter_ctrl()``) are being deprecated. In gatekeeper, we use them to add EtherType filters as well as ntuple filters. To fully update to the latest DPDK, we need to deprecate these function calls, and instead we will use the generic filter APIs.

This issue relates to #272

**Comment by AltraMayor** [comment]
Is it possible to just replace these calls with their corresponding calls in the filter API? Or does it require a rewrite of some part of Gatekeeper?

**Comment by mengxiang0811** [comment]
We need to use the [generic flow API](https://doc.dpdk.org/api/rte__flow_8h.html) to replace the above functions. I will give an update after reviewing these APIs as it seems not simple replace.

**Comment by AltraMayor** [comment]
This issue should also remove `-Wno-deprecated-declarations` from the variable `EXTRA_CFLAGS` in the `Makefile.
