### ISSUE TITLE
Follow network order on packet headers in policies

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#304]
One should review our example Lua policy to make sure that all fields of packet headers larger than one byte are converted from network to host order before their use. Currently, the port numbers of TCP and UDP headers are being used directly. One must review the whole policy to check if there is no other case in which this bug happens.

Even if not all the following functions are needed to fix the issues above, we should export to Lua the following DPDK functions:
* `rte_cpu_to_be_16()`
* `rte_cpu_to_be_32()`
* `rte_be_to_cpu_16()`
* `rte_be_to_cpu_32()`

Given that the pull request #295 is going to be merged soon, it'll save work to write this pull request in reference to it as explained in this comment [here](https://github.com/AltraMayor/gatekeeper/issues/230#issuecomment-507661857).

**Comment by mengxiang0811** [comment]
The source and destination IP addresses are used by LPM should keep the network order, as our c APIs will convert them to host order as necessary.
