### ISSUE TITLE
Solicitor block's token bucket refilling incorrectly

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#312]
The credits in the token bucket algorithm of the Solicitor block appears to be refilling too quickly, and therefore the allocated bandwidth of the request channel is not precise.

**Gatekeeper config**

I'm testing the precision of the algorithm by setting the request channel bandwidth to be 81.92 Kbps in `lua/sol.lua`:

```
local req_channel_bw_mbps = .08192
```

This is equivalent to 81920 bits per second, or 10240 bytes per second. That's enough to handle 10 packets of length 1024 every second.

**Client config**

I generate packets using `hping3` with this command:

```
sudo hping3 -c 1000 -n -i u100000 --udp -p 8080 172.32.3.200 -d 938
```

This generates 1000 UDP packets to the specified port and IP address (the Gatekeeper server). The `-i u100000` means to wait 100000 microseconds (100 milliseconds) between packets, which means 10 will be sent every second. The length of the data payload is 938 bytes, as after all headers and encapsulations the frame will be 1024 bytes to send to Grantor. 10 packets of length 1024 every second means we'll be sending at a rate of 81.92 Kbps.

**Experiments**

With this experiment, Gatekeeper should in theory be able to handle all the packets in the request channel, and it does -- no packets are dropped or made to wait for another iteration in the request queue.

But keeping the same Gatekeeper settings (request channel at a rate of 81.92 Kbps), I try sending at twice the rate:

```
sudo hping3 -c 1000 -n -i u50000 --udp -p 8080 172.32.3.200 -d 938
```

Since we now have `-i u50000`, the program waits 50000 microseconds (or 50 milliseconds) between packets, so that we can send 20 packets per second. This means we will be sending at a rate of 163.84 Kbps, which is twice the allotted 81.92 Kbps for the request channel.

However, no packets are dropped and none are made to wait in the request queue. I think at this rate roughly half should be made to wait. I then did the same test at 50 Kbps, 100 Kbps, 200 Kbps, 500 Kbps, and no packets were made to wait. At 1 Mbps, packets were made to wait 1200 times but none of them were actually dropped (the request queue never became full). 

**Investigating why**

I first found a bug in the calculation of the number of available bytes that was refilling the bucket way too quickly (by billions). This helped make the refill rate more reasonable, but I am still observing the same problem described above.

Some potential reasons:

_Reason 1_
The CPU cycles per second calculation is not correct. We calculate it to be about 2.5 GHz on the machine I'm using (which is what the CPU is rated at), but looking at `/proc/cpuinfo`, it actually reads closer to 3.1 GHz. I tried putting this literal into the code instead of `cycles_per_second` for the token bucket calculation, and it maybe helped slightly but not fully. The 20 Kbps test still doesn't have any packets made to wait in the request queue for another iteration.

_Reason 2_
The timing or rate at which we're calling the `credits_update()` function is not accurately refilling the bucket. I logged the timing of how credits are removed and added, and I'm attaching the log for the 10 Kbps experiment and the 50 Kbps experiment.

Note that there is a pattern to how the bucket is refilled: we most often only have enough cycles for 1 byte at a time, but when we're about to dequeue packets, many more cycles pass and the token bucket is filled with hundreds or thousands of bytes. I think the time we're taking to enqueue packets into the request queue from the GK block is taking too long and the bucket is refilling during that time. I don't think this quite explains why we're able to process 500 Kbps when we're only allowing for 10 Kbps, though.

Note about the logs: my logs only log when credits are removed due to sending packets, and when credits are added to a not-full bucket. It doesn't log anything when `credits_update()` is called but does nothing because not enough cycles are passed, and it doesn't log anything when `credits_update()` is called and the bucket is already full.

[10kbps_longer.txt](https://github.com/AltraMayor/gatekeeper/files/3373789/10kbps_longer.txt)
[50kbps_longer.txt](https://github.com/AltraMayor/gatekeeper/files/3373790/50kbps_longer.txt)

**Comment by AltraMayor** [comment]
Reading the log, I see that whenever we are close to sending a packet out, we add a lot of even more credit that the size of the packet to be forwarded. My best guess to explain this is that the solicitor is waiting on a lock somewhere. We can test this hypothesis making the solicitor sleep in each iteration of its loop.

**Comment by cjdoucette** [comment]
Sorry, not sure I'm grasping the suggestion. If the Solicitor is waiting on a lock somewhere, why would adding a sleep reveal that?

**Comment by AltraMayor** [comment]
The loop in `sol_proc()` is tight. So, if there's a lock contention between the SOL and a GK block, it'd be because the SOL block is always checking the lock. If the SOL block sleeps even a little bit at each iteration, the probability of reducing the lock contention should significantly drop. This wouldn't be a solution, the idea is to just (hopefully) identify the problem.

**Comment by cjdoucette** [comment]
Adding a 100ns sleep between enqueuing and dequeuing causes the block refill to be more uniform:

```
Trying to send a request of length 1024 and the number of credits is 10240
Number of credits is now 9216
Updating credits: currently have 9216 credits and adding 121
Updating credits: currently have 9337 credits and adding 296
Updating credits: currently have 9633 credits and adding 217
Updating credits: currently have 9850 credits and adding 126
Updating credits: currently have 9976 credits and adding 394
Trying to send a request of length 1024 and the number of credits is 10240
Number of credits is now 9216
Updating credits: currently have 9216 credits and adding 50
Updating credits: currently have 9266 credits and adding 410
Updating credits: currently have 9676 credits and adding 417
Updating credits: currently have 10093 credits and adding 135
Updating credits: currently have 10228 credits and adding 503
Trying to send a request of length 1024 and the number of credits is 10240
Number of credits is now 9216
Updating credits: currently have 9216 credits and adding 324
Updating credits: currently have 9540 credits and adding 416
Updating credits: currently have 9956 credits and adding 9
Updating credits: currently have 9965 credits and adding 482
Trying to send a request of length 1024 and the number of credits is 10240
Number of credits is now 9216
Updating credits: currently have 9216 credits and adding 114
Updating credits: currently have 9330 credits and adding 330
Updating credits: currently have 9660 credits and adding 289
Updating credits: currently have 9949 credits and adding 286
Updating credits: currently have 10235 credits and adding 410
Trying to send a request of length 1024 and the number of credits is 10240
Number of credits is now 9216
Updating credits: currently have 9216 credits and adding 30
Updating credits: currently have 9246 credits and adding 484
Updating credits: currently have 9730 credits and adding 3
```

Nothing more than ~500 bytes is added a time, though while generating twice the request channel bandwidth still no requests are made to wait or dropped.

**Comment by AltraMayor** [comment]
Could you add time and cycle information to the log entries? This information may add some insight.

The log above at least suggests that the credit algorithm is correct since the bytes added between packets (i.e. 100ms) is adding ~1024 bytes to the bucket:
```
121+296+217+126+394=1154
324+416+9+482=1231
```

**Comment by cjdoucette** [comment]
Attaching another log, where I'm sending at 20 KBps (20 packets each with 1024 B every second).

I'm overlooking something or I've made a wrong assumption somewhere, but it's just not adding up at the moment.

[20kbps_longer_100nsleep.txt](https://github.com/AltraMayor/gatekeeper/files/3375085/20kbps_longer_100nsleep.txt)

**Comment by cjdoucette** [comment]
I think there might be a bug in our accounting of spare cycles/saving the last CPU cycles measurement, and it is causing the delta in cycles between updates to be too large.

**Comment by AltraMayor** [comment]
I agree. Update the last line of `credits_update()` with this assignment to correct it:
```req_queue->time_cpu_cycles = curr_cycles - avail_bytes.rem / req_queue->cycles_per_byte_b;```

**Comment by cjdoucette** [comment]
This seems to fix the issue, and also gets rid of the behavior of having many more credits added just before a packet arrives.

Now almost all credit updates are for either 0 or 1 credit, with only a handful of updates that add more throughout the length of the experiment I ran:

```
time: 1562770424, cycles: 7746945182973996 (diff of 1141714): Updating credits: currently have 24
1 credits and adding 4
time: 1562770430, cycles: 7746960271739436 (diff of 19083224): Updating credits: currently have 5
31 credits and adding 78
time: 1562770436, cycles: 7746975041886074 (diff of 37498226): Updating credits: currently have 5
38 credits and adding 153
time: 1562770443, cycles: 7746991123010756 (diff of 18988818): Updating credits: currently have 9
46 credits and adding 77
time: 1562770443, cycles: 7746991404855888 (diff of 13724141): Updating credits: currently have 7
4 credits and adding 56
time: 1562770443, cycles: 7746991405355468 (diff of 551830): Updating credits: currently have 130
 credits and adding 2
time: 1562770449, cycles: 7747007728520118 (diff of 693361): Updating credits: currently have 429
 credits and adding 2
time: 1562770449, cycles: 7747007746718272 (diff of 18159092): Updating credits: currently have 4
32 credits and adding 74
time: 1562770491, cycles: 7747111458326792 (diff of 50165007): Updating credits: currently have 1
43 credits and adding 205
time: 1562770491, cycles: 7747111515244624 (diff of 57033953): Updating credits: currently have 348 credits and adding 233
```

I'll issue a patch soon.

**Comment by AltraMayor** [comment]
There should be no `adding 0` since there's a protection against it at the beginning of `credits_update()`.

**Comment by cjdoucette** [comment]
Right, I meant that almost all calls to `credits_update()` result in 0 or 1 credits being added, but I'm not seeing any logs that have `adding 0`.
