### ISSUE TITLE
Batched hash table lookups (i.e., rte_hash_lookup_bulk()) with hash re-computation vs single lookups with pre-computed hashes?

### ISSUE THREAD

**Issue by mengxiang0811** [AltraMayor/gatekeeper#339]
As pointed out in the [comment](https://github.com/AltraMayor/gatekeeper/pull/330#discussion_r314048439), when we try to adopt the batched hash table lookups (i.e., ``rte_hash_lookup_bulk()``), it doesn't take advantages of the available pre-computed hashes via NICs.

We need a patch that enables us to test the difference to choose between them, i.e., either to do batched lookups with hash re-compuation or to do single lookups with pre-computed hashes.

**Comment by mengxiang0811** [comment]
Through our [evaluation](https://github.com/AltraMayor/gatekeeper/pull/330#issuecomment-532406527), we know that the batched hash table lookups with hash re-computation performs worse than the single lookups with pre-computed hashes. However, with [batched hash table lookups with pre-computed hashes](https://github.com/AltraMayor/gatekeeper/pull/330#issuecomment-534167213), we see performance improvement up to ``3.3x``.

**Comment by AltraMayor** [comment]
This issue has been solved in Gatekeeper's version of DPDK. One can find the patch at https://github.com/cjdoucette/dpdk/pull/13 .
