### ISSUE TITLE
Type mismatch in Lua IPv6 LPM lookup

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#379]
https://github.com/AltraMayor/gatekeeper/blob/82783020a0df351e86ea2d6b2f444bdaf00d7aad/lua/examples/policy.lua#L163-L165

There is a type mismatch in the above Lua policy code when we try to do an LPM lookup on IPv6 addresses. The type of `struct rte_ipv6_hdr.src_addr` is a `uint8_t [16]`, not a `struct in6_addr`. Therefore, when we call `lpm6_lookup()`, we get this error:

```
GATEKEEPER GT: Error running function `lookup_policy': ./lua/examples/policy.lua:165: Expected `struct in6_addr &' as second argument, at lcore 1
```

Note that we do not have this issue with `lpm6_add()` because we use `str_to_prefix6()` to build a `struct in6_addr`.

This bug was not caught earlier because of a related bug (#378), in which Grantor was reading IPv6 packet priorities incorrectly, causing it to think that all packets were granted.

**Comment by cjdoucette** [comment]
I tried changing the `struct in6_addr *` to be a `uint8_t *`, but I got the same error. Anybody know what we will need to do to match the array type?

**Comment by mengxiang0811** [comment]
The error message may come from the Lua C function [l_lpm6_lookup()](https://github.com/AltraMayor/gatekeeper/blob/master/gt/lua_lpm.c#L317-L323). We may have to change the ``ctypeid`` (i.e., ``CTYPE_STRUCT_IN6_ADDR_REF``) to a different one. Or, we may have another Lua C function converting the IPv6 address to ``struct in6_addr`` from ``uint8_t *``.

**Comment by AltraMayor** [comment]
@mengxiang0811 is right, the bug is at `l_lpm6_lookup()`. The solution is to support `struct in6_addr &` and `struct in6_addr *` in `l_lpm6_lookup()`. Our code should have enough information to figure out how to do that.
