### ISSUE TITLE
I have issue while stacking the network any solution? Also i am a bit confuse about grantor server how to install?

### ISSUE THREAD

**Issue by Ranzanregmi** [AltraMayor/gatekeeper#409]

**Comment by AltraMayor** [comment]
HI @Ranzanregmi,

Could you describe the issue you are having? For example, describe what you intend to set up, the environment (e.g. machines, topology), error messages, etc.

The binary `gatekeeper` can run as a Gatekeeper server or as a Grantor server; this choice is defined in the configuration file `main_config.lua`. Seer variable `gatekeeper_server` [here](https://github.com/AltraMayor/gatekeeper/blob/abb3442d0cf17a2b8404897cb40ba60a06b6e91a/lua/main_config.lua#L13). If you have installed Gatekeeper from the packages, you find the file `main_config.lua` in folder `/etc/gatekeeper`.
