### ISSUE TITLE
Gatekeeper networking questions

### ISSUE THREAD

**Issue by dahnevskiy** [AltraMayor/gatekeeper#413]
Hello,

I read all the documentation but couldn 't find answers to some questions:

1. gatekeeper need to send traffic to grantor server through back interface, but how  gatekeeper server learns the grantor ip address? in network settings, when i configure gatekeeper service, i cant find, where i need to specify grantor ip address. 
2. Can i use bird.conf to configure bgp neighbors, if i use port 0x6A7E in bird configuration? Or i need to use some gatekeeper config for this purpose? 
3. Can BGP session be established, using front interfaces, which is controlled by dpdk? Or i need another link to border router, which is controlled by OS kernel driver for control plane?

**Comment by AltraMayor** [comment]
These are good questions, @dahnevskiy! I'm going to add them to our FAQ page. Thank you for taking the time to evaluate Gatekeeper.

1. This information is passed to Gatekeeper servers dynamically to quickly accommodate network changes. You can see an example in file [`lua/examples/example_of_dynamic_config_request.lua`](https://github.com/AltraMayor/gatekeeper/blob/master/lua/examples/example_of_dynamic_config_request.lua). Search for `GK_FWD_GRANTOR`; there's an example for IPv4 and another for IPv6. You can use [`gkctl`](https://github.com/AltraMayor/gatekeeper/blob/master/gkctl/main.c) to send these commands.

2. There's no restriction on how you set Bird up. The patch we added to Bird is to switch from talking to the kernel to talk to Gatekeeper, so Gatekeeper receives the computed routing table. The patch is small and potentially useful for other projects, so we hope to get it upstream once we have time to work with the developers of Bird.

3. The Control Plane Support (CPS) block creates network interfaces in the kernel that mirror the front and back networks. Thus, once can set Bird up over these interfaces to establish BGP sessions with routers on both sides of Gatekeeper. These interfaces are called KNI interfaces.

**Comment by cjdoucette** [comment]
I will also add that in response to (1) you might find this description helpful:

https://github.com/AltraMayor/gatekeeper/wiki/Functional-Block:-GK#Adding_and_Deleting_FIB_Entries

**Comment by dahnevskiy** [comment]
Thanks for quick response and help!

I forgot to ask:
What i need to do, if i want to protect /32 host, using gatekeeper?
as i can see, i only need to announce this /32, using BGP, to network. And thats all.
thats right?

**Comment by AltraMayor** [comment]
In theory, yes. In practice, the smallest prefix that is not subject to a prefix-length filter in the open Internet is /24. This is an arbitrary setup of BGP that is widely used.

If you have a /24 prefix or larger to announce, all you have to do is to inform Gatekeeper servers the prefix you want to protect, which could be the whole announced prefix or less. For example, if you announce 10.0.0.0/8, you can protect the whole prefix, just 10.0.0.1/32, or anything in between.

If you don't have a /24 prefix or larger to announce, Gatekeeper may not be for you. And you may be better off hiring a protection company.

If you don't have a /24 prefix or larger to announce and still want to try Gatekeeper anyway, it seems that the company [Datapath.io](https://datapath.io/) can help. It seems that they go around the BGP limitation explained above by announcing their own IP prefixes and lending a single IP address to their customers through their routing service. I don't really know the company, so I may be wrong here.

**Comment by dahnevskiy** [comment]
Ok, thanks.

I dont need to announce /32 route to open internet.
To open internet i will announce /24 or less specific network.

After traffic will reach our internal network, i can use /32 announce inside our internal network to route traffic to my gatekeeper servers.

**Comment by AltraMayor** [comment]
That setup is fine.
