### ISSUE TITLE
Adopt rte_pktmbuf_free_bulk()

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#435]
More recent versions of DPDK add the ability to do a bulk freeing of packets. We should adopt it into Gatekeeper when we upgrade DPDK.

**Comment by AltraMayor** [comment]
While working on this issue, one should investigate all calls to `rte_pktmbuf_free()` since there're a number of opportunities to use `rte_pktmbuf_free_bulk()` in the code.
