### ISSUE TITLE
Failed to start Gatekeeper DDoS protection system.

### ISSUE THREAD

**Issue by FrankensteinEvil0069** [AltraMayor/gatekeeper#472]
I followed your instructions correctly and properly installed the tool on my system, But I got this error please check this out <br><br>
┌─[✗]─[root@kali-linux]─[~/DDOS/gatekeeper/gatekeeper-ubuntu-18.04-packages]
└──╼ #sudo systemctl status gatekeeper 
● gatekeeper.service - Gatekeeper DDoS protection system
     Loaded: loaded (/lib/systemd/system/gatekeeper.service; enabled; vendor preset: disabled)
     Active: failed (Result: signal) since Wed 2021-04-28 00:09:57 IST; 3min 5s ago
   Main PID: 75049 (code=killed, signal=ILL)
        CPU: 745ms

Apr 28 00:09:57 shreyas-kali-linux systemd[1]: gatekeeper.service: Scheduled restart job, restart counter is at 5.
Apr 28 00:09:57 shreyas-kali-linux systemd[1]: Stopped Gatekeeper DDoS protection system.
Apr 28 00:09:57 shreyas-kali-linux systemd[1]: gatekeeper.service: Start request repeated too quickly.
Apr 28 00:09:57 shreyas-kali-linux systemd[1]: gatekeeper.service: Failed with result 'signal'.
Apr 28 00:09:57 shreyas-kali-linux systemd[1]: Failed to start Gatekeeper DDoS protection system.

<br>  Please help me with this issue

**Comment by andrenth** [comment]
Hello

When you install Gatekeeper using the Debian packages, the configuration files are installed in the `/etc/gatekeeper` directory. You should edit at least `net.lua` and set the `front_ports`, `front_ips`, `back_ports` and `back_ips` variables according to your environment.

You also need to edit `/etc/gatekeeper/envvars` and set the `GATEKEEPER_INTERFACES` variable with the PCI addresses of the front and back ports. You can obtain this information with the `lshw -c network -businfo` command.

For example, if your front and back ports are `eth0` and `eth1`, then you might get an output like this:

```
# lshw -c network -businfo
Bus info          Device     Class          Description
=======================================================
pci@0000:08:00.0  eth0       network        I350 Gigabit Network Connection
pci@0000:08:00.1  eth1       network        I350 Gigabit Network Connection
...
```

in which case you would set

```
GATEKEEPER_INTERFACES="08:00.0 08:00.1"
```

in `/etc/gatekeeper/envvars`.

After these settings you should be able to start the gatekeeper service, or at least get a more meaninful error in `/var/log/gatekeeper`.

HTH
