### ISSUE TITLE
Have all log accounted on a functional block basis

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#497]
Currently, each functional block type of Gatekeeper has a log level. This approach is meant to help those investigating a functional block since one would only raise the log level of the target block. However, this approach can run into the following issue: when a block calls functions provided by another block, these functions are potentially subject to another log level.

Consider the following example, one is investigating the communication between a routing daemon and the CPS block. The CPS block will make a number of calls to the FIB functions that the GK block provides. Raising the log level of the CPS block won't affect the FIB functions. And raising the log level of the GK block to affect the FIB functions will include a lot of log entries from the GK blocks that are not related to the calls from the CPS block.

A solution for this problem is for all log entries to use the log level of the calling block instance. This change may sound complicated at first, however, given that all block instances already have a log rate, the change won't add new infrastructure but an extension of the log rate subsystem. Thus, after the change, each block instance would have a log rate and a log level.

While the improvement proposed above seems desirable, it requires tests in production to make sure that it is so.

**Comment by AltraMayor** [comment]
If implemented, the solution should also offer a replacement for `staticlib.c.rte_log_set_level()` currently being used to dynamically change the log level of blocks. See [file `example_of_dynamic_config_request.lua`](https://github.com/AltraMayor/gatekeeper/blob/master/lua/examples/example_of_dynamic_config_request.lua) for an example.

**Comment by AltraMayor** [comment]
Blocks should be identified by a short string (as suggested above) in order to use this string to identify which block logged each log entry. This would avoid ambiguous logging like the following entry:
`GATEKEEPER GT: /etc/gatekeeper/policy.lua:239: gt: failed to initialize the IPv6 LPM table for Lua policies`

The log entry above identifies the GT block because it implements `l_update_gt_lua_states()`, but the actual caller is the dynamic configuration block.

This approach solves two problems other issues:
1. It avoids block anonymous log entries. For example: `GATEKEEPER: 99 log entries were suppressed at lcore 9 during the last ratelimit interval`;
2. It forgoes the need to have multiple logging macros since each block logs its name.

**Comment by mengxiang0811** [comment]
One idea to implement this is that we add a `log_level`, a `log_type`, and a `block_name` inside each `log_ratelimit_state` entry on a lcore. Since we will have new functions to dynamically set the log level on per-block/per-lcore basis, we will have to use a lock to protect the state of each `log_ratelimit_state` entry. What do you think?

**Comment by AltraMayor** [comment]
I agree with that idea, but why would we need `log_type`? I understand that there'll be a single logging macro, so the type will be the same for all lcores. We could use the type `RTE_LOGTYPE_USER1` for this purpose.

About the lock, I think we can avoid it using an atomic type. This should be better because the vast majority of times that the log level will be accessed is to read it.

**Comment by mengxiang0811** [comment]
If we only use one `log_type` (e.g., `RTE_LOGTYPE_USER1`) for all lcores, and different functional blocks could have different `log_level`, how would we deal with these scenarios as we could only have one `log_type` for each `log_level` at a single point of time?

Having a `log_type` in the state, we could set the `log_level` for each lcore. If we want to set the `log_level` for a functional block (e.g., `GK`), we could iterate over all `log_ratelimit_state` entries belonging to the block `GK`.

**Comment by AltraMayor** [comment]
I understood your point, but, as I understand it, there's no material advantage in having a log type per lcore since we can set the chosen, single log type to have log level `RTE_LOG_DEBUG` and test the log level of the lcore before calling the function that actually logs. The added overhead is not really there since our code has to rate limit log and the log level will be in the cache then. Avoiding multiple log types may even simplify the code.

**Comment by AltraMayor** [comment]
Pull request #536 is pushing this issue forward.

**Comment by AltraMayor** [comment]
@mengxiang0811, once the code is about to fulfill all the requirements of this issue, please test Gatekeeper to see how the log registered during initialization is being logged. Initialization may require attention because no block is running then.

**Comment by AltraMayor** [comment]
Pull request #537 is pushing this issue forward.

**Comment by AltraMayor** [comment]
Pull request #539 is pushing this issue forward.
