### ISSUE TITLE
There is not enough lcores

### ISSUE THREAD

**Issue by shirley04** [AltraMayor/gatekeeper#507]
run gatekeeper ,report error    (I have bounded 0000:03:00.0 & 0000:0b:00.0 to dpdk
EAL: Detected 6 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: PCI device 0000:0b:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: PCI device 0000:13:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: See files in . for further log

cat log
GATEKEEPER: main: cycles/second = 2099998103, cycles/millisecond = 2099998, picosec/cycle = 476
GATEKEEPER: config: ./lua/gatekeeper/staticlib.lua:106: There is not enough lcores
GATEKEEPER: main: failed to configure Gatekeeper
~

**Comment by AltraMayor** [comment]
The total number of lcores, or logical cores, is the total number of cores from all processors on a machine. If those processors have hyperthread enabled, you double the number of cores to obtain the number of lcores. The machine you used to test Gatekeeper has 6 lcores (see log entry `EAL: Detected 6 lcore(s)`). The needed number of lcores depends on how Gatekeeper is configured. On a typical two-processor machine, Gatekeeper needs 10 lcores as a Gatekeeper server, or 5 locres as a Grantor server.

**Comment by shirley04** [comment]
It worked when I changed the 5 lcores to 10 locres.
