### ISSUE TITLE
: failed to configure port 0

### ISSUE THREAD

**Issue by shirley04** [AltraMayor/gatekeeper#509]
GATEKEEPER CPS: init_kni: /lib/modules/5.4.0-33-generic/updates/dkms/rte_kni.ko already inserted
GATEKEEPER: net: port 0 (0000:00:08.0) on the front interface does not support to get RSS configuration, disable RSS
GATEKEEPER: net: port 0 (0000:00:08.0) on the front interface doesn't support offloading IPv4 checksumming; will use software IPv4 checksums
GATEKEEPER: net: the front interface does not have RSS capabilities; the GK or GT block will receive all packets and send them to the other blocks as needed. Gatekeeper or Grantor should only be run with one lcore dedicated to GK or GT in this mode; restart with only one GK or GT lcore if necessary
Ethdev port_id=0 nb_tx_queues=3 > 1
GATEKEEPER: net: failed to configure port 0 (0000:00:08.0) on the front interface (err=-22)
~

**Comment by AltraMayor** [comment]
Hi @shirley04,

Is this issue happening on a virtual NIC like in issue #508 that you've opened? If so, see my answer there.

**Comment by shirley04** [comment]
I create another vm in kvm, and the nic is Virtio

root@security-gk2:~/src/gatekeeper# dependencies/dpdk/usertools/dpdk-devbind.py --status-dev net

Network devices using DPDK-compatible driver
============================================
0000:00:04.0 'Virtio network device 1000' drv=igb_uio unused=vfio-pci
0000:00:05.0 'Virtio network device 1000' drv=igb_uio unused=vfio-pci

Network devices using kernel driver
===================================
0000:00:03.0 'Virtio network device 1000' if=ens3 drv=virtio-pci unused=igb_uio,vfio-pci *Active*
0000:00:06.0 'Virtio network device 1000' if=ens6 drv=virtio-pci unused=igb_uio,vfio-pci

**Comment by AltraMayor** [comment]
We do not support virtual NICs at this point. For more on this see my comment [here](https://github.com/AltraMayor/gatekeeper/issues/508#issuecomment-885590993).
