### ISSUE TITLE
 no appropriate memory area found in which to create memzone

### ISSUE THREAD

**Issue by shirley04** [AltraMayor/gatekeeper#516]
1.cat log:
GATEKEEPER: net: port 1 (0000:62:00.1) on the front interface only supports RSS hash functions 0x38d34, but Gatekeeper asks for 0xa38c
GATEKEEPER: net: port 0 (0000:62:00.0) on the back interface only supports RSS hash functions 0x38d34, but Gatekeeper asks for 0xa38c
GATEKEEPER: lls: calculate_mempool_config_para: total_pkt_burst = 2144 packets, total_rx_desc = 640 descriptors, total_tx_desc = 256 descriptors, max_num_pkt = 3040 packets, num_mbuf = 4095 packets.
GATEKEEPER: gk: calculate_mempool_config_para: total_pkt_burst = 632 packets, total_rx_desc = 640 descriptors, total_tx_desc = 256 descriptors, max_num_pkt = 1528 packets, num_mbuf = 2047 packets.
GATEKEEPER: net: failed to allocate mbuf for block gk at lcore 3
GATEKEEPER: no appropriate memory area found in which to create memzone

______________________________________________________________________________________________
2.when I set  local front_num_tx_desc = 512  & local back_num_tx_desc = 512   in  lua/net.lua 
report error
cat log:
GATEKEEPER: lls: calculate_mempool_config_para: total_pkt_burst = 2144 packets, total_rx_desc = 640 descriptors, total_tx_desc = 1024 descriptors, max_num_pkt = 3808 packets, num_mbuf = 4095 packets.
GATEKEEPER: gk: calculate_mempool_config_para: total_pkt_burst = 632 packets, total_rx_desc = 640 descriptors, total_tx_desc = 1024 descriptors, max_num_pkt = 2296 packets, num_mbuf = 4095 packets.
GATEKEEPER: mailbox: can't create mempool gk_mailbox_pool_2 (len = 17) at lcore 2
GATEKEEPER GK: Failed to setup gk instances for GK block at lcore 2
RING: Cannot free ring, not created with rte_ring_create()

_______________________________________________
 /usr/bin/dpdk-devbind.py --status-dev net

Network devices using DPDK-compatible driver
============================================
0000:62:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection 10fb' drv=uio_pci_generic unused=ixgbe,igb_uio,vfio-pci
0000:62:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection 10fb' drv=uio_pci_generic unused=ixgbe,igb_uio,vfio-pci

**Comment by AltraMayor** [comment]
Hi @shirley04,

How much RAM does your server have? How much did you allocate for huge tables? How many processors are installed on the motherboard?
