### ISSUE TITLE
can not receive packets

### ISSUE THREAD

**Issue by shirley04** [AltraMayor/gatekeeper#519]
```
GATEKEEPER GK: The GK block basic measurements at lcore = 2: [tot_pkts_num = 0, tot_pkts_size = 0, pkts_num_granted = 0, pkts_size_granted = 0, pkts_num_request = 0, pkts_size_request =  0, pkts_num_declined = 0, pkts_size_declined =  0, tot_pkts_num_dropped = 0, tot_pkts_size_dropped =  0, tot_pkts_num_distributed = 0, tot_pkts_size_distributed =  0]
GATEKEEPER GK: The GK block basic measurements at lcore = 3: [tot_pkts_num = 0, tot_pkts_size = 0, pkts_num_granted = 0, pkts_size_granted = 0, pkts_num_request = 0, pkts_size_request =  0, pkts_num_declined = 0, pkts_size_declined =  0, tot_pkts_num_dropped = 0, tot_pkts_size_dropped =  0, tot_pkts_num_distributed = 0, tot_pkts_size_distributed =  0]
GATEKEEPER GK: The GK block basic measurements at lcore = 12: [tot_pkts_num = 0, tot_pkts_size = 0, pkts_num_granted = 0, pkts_size_granted = 0, pkts_num_request = 0, pkts_size_request =  0, pkts_num_declined = 0, pkts_size_declined =  0, tot_pkts_num_dropped = 0, tot_pkts_size_dropped =  0, tot_pkts_num_distributed = 0, tot_pkts_size_distributed =  0]
GATEKEEPER GK: The GK block basic measurements at lcore = 13: [tot_pkts_num = 0, tot_pkts_size = 0, pkts_num_granted = 0, pkts_size_granted = 0, pkts_num_request = 0, pkts_size_request =  0, pkts_num_declined = 0, pkts_size_declined =  0, tot_pkts_num_dropped = 0, tot_pkts_size_dropped =  0, tot_pkts_num_distributed = 0, tot_pkts_size_distributed =  0]
GATEKEEPER LLS: LLS cache (arp)
=====================
GATEKEEPER LLS: 10.11.97.1: 94:24:e1:26:16:01 (port 0) (0 holds)
GATEKEEPER LLS: LLS cache (nd)
=====================
GATEKEEPER LLS: LLS cache (arp)
=====================
GATEKEEPER LLS: 10.11.97.1: 94:24:e1:26:16:01 (port 0) (0 holds)
GATEKEEPER LLS: 10.11.97.57: 00:0c:29:98:c5:5e (port 1) (0 holds)
PANIC in lookup_fe_from_lpm():
line 1466       assert "eth_cache != NULL" failed
7: [/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f8a010ee293]]
6: [/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f8a011c7609]]
5: [build/gatekeeper(+0xcf2e4) [0x559972fa42e4]]
4: [build/gatekeeper(+0x281d6f) [0x559973156d6f]]
3: [build/gatekeeper(+0xb76ac) [0x559972f8c6ac]]
2: [build/gatekeeper(__rte_panic+0xcd) [0x559972fa5654]]
1: [build/gatekeeper(rte_dump_stack+0x32) [0x5599732996a2]]
```

**Comment by AltraMayor** [comment]
Hi @shirley04,

Could you provide more information about your setup? For example, which version are you running? The latest version of Gatekeeper on our repository doesn't have the test `"eth_cache != NULL"` at line 1466 (this information is from your log above), but at line 1417 and line 1452. You can check those lines of `lookup_fe_from_lpm()` [here](https://github.com/AltraMayor/gatekeeper/blob/b6835905d085dc55623709b5cc64af28e61ec0ad/gk/main.c#L1417-L1466). Until we release an official stable version, please stick to the latest, so we can track issues.

Moreover, can you describe the topology you're building? Can you share your file `lua/net.lua`? What else have you changed in the configuration that comes with Gatekeeper?

**Comment by shirley04** [comment]
development 
![image](https://user-images.githubusercontent.com/65704390/128843283-06c8d45d-efa2-47be-b929-943c43ea9a2a.png)
_________________________________________________________________________________
vi lua/net.lua
   local front_ports = {"enp98s0f1"}
        local front_ips  = {"10.11.97.11/24", "2001:db8:1::1/48"}
        local front_bonding_mode = staticlib.c.BONDING_MODE_ROUND_ROBIN
        local front_ipv4_vlan_tag = 0x123
        local front_ipv6_vlan_tag = front_ipv4_vlan_tag
        local front_vlan_insert = false
        local front_mtu = 1500

        local back_ports = {"enp98s0f0"}
        local back_ips  = {"10.11.97.10/24", "2001:db8:2::1/48"}
        local back_bonding_mode = staticlib.c.BONDING_MODE_ROUND_ROBIN
        local back_ipv4_vlan_tag = 0x456
        local back_ipv6_vlan_tag = back_ipv4_vlan_tag
        local back_vlan_insert = false
        local back_mtu = 2048

        -- XXX #155 These parameters should only be changed for performance reasons.
        local front_arp_cache_timeout_sec = 7200 -- (2 hours)
        local front_nd_cache_timeout_sec = 7200  -- (2 hours)
        local front_num_rx_desc = gatekeeper_server and 512 or 128
        local front_num_tx_desc = 512

        local back_arp_cache_timeout_sec = 7200  -- (2 hours)
        local back_nd_cache_timeout_sec = 7200   -- (2 hours)
        local back_num_rx_desc = 128
        local back_num_tx_desc = 512
______________________________________________________________________________

I updated to the latest version , When I ping the ip of kni_front , report  error 
cat log:
GATEKEEPER GK: The GK block basic measurements at lcore = 13: [tot_pkts_num = 0, tot_pkts_size = 0, pkts_num_granted = 0, pkts_size_granted = 0, pkts_num_request = 0, pkts_size_request =  0, pkts_num_declined = 0, pkts_size_declined =  0, tot_pkts_num_dropped = 0, tot_pkts_size_dropped =  0, tot_pkts_num_distributed = 0, tot_pkts_size_distributed =  0]
GATEKEEPER GK: The GK block basic measurements at lcore = 2: [tot_pkts_num = 0, tot_pkts_size = 0, pkts_num_granted = 0, pkts_size_granted = 0, pkts_num_request = 0, pkts_size_request =  0, pkts_num_declined = 0, pkts_size_declined =  0, tot_pkts_num_dropped = 0, tot_pkts_size_dropped =  0, tot_pkts_num_distributed = 0, tot_pkts_size_distributed =  0]
GATEKEEPER GK: The GK block basic measurements at lcore = 3: [tot_pkts_num = 0, tot_pkts_size = 0, pkts_num_granted = 0, pkts_size_granted = 0, pkts_num_request = 0, pkts_size_request =  0, pkts_num_declined = 0, pkts_size_declined =  0, tot_pkts_num_dropped = 0, tot_pkts_size_dropped =  0, tot_pkts_num_distributed = 0, tot_pkts_size_distributed =  0]
GATEKEEPER GK: The GK block basic measurements at lcore = 12: [tot_pkts_num = 0, tot_pkts_size = 0, pkts_num_granted = 0, pkts_size_granted = 0, pkts_num_request = 0, pkts_size_request =  0, pkts_num_declined = 0, pkts_size_declined =  0, tot_pkts_num_dropped = 0, tot_pkts_size_dropped =  0, tot_pkts_num_distributed = 0, tot_pkts_size_distributed =  0]
GATEKEEPER LLS: LLS cache (arp)
=====================
GATEKEEPER LLS: 10.11.97.1: 94:24:e1:26:16:01 (port 0) (0 holds)
GATEKEEPER LLS: 10.11.97.2: b4:09:31:e1:45:89 (port 1) (0 holds)
GATEKEEPER LLS: 10.11.97.57: 00:0c:29:98:c5:5e (port 1) (0 holds)
GATEKEEPER LLS: LLS cache (nd)
=====================
PANIC in lookup_fe_from_lpm():
line 1452       assert "eth_cache != NULL" failed
7: [/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fdeae940293]]
6: [/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7fdeaea19609]]
5: [build/gatekeeper(+0xcf3ff) [0x561dd20a33ff]]
4: [build/gatekeeper(+0x282d9f) [0x561dd2256d9f]]
3: [build/gatekeeper(+0xb776c) [0x561dd208b76c]]
2: [build/gatekeeper(__rte_panic+0xcd) [0x561dd20a476f]]
1: [build/gatekeeper(rte_dump_stack+0x32) [0x561dd2399712]]

**Comment by AltraMayor** [comment]
Hi @shirley04,

The front and back interfaces of Gatekeeper cannot be neighbors, that is, they must be in different subnets. This is necessary to guarantee that attackers cannot bypass Gatekeeper. In your setup, they are in the same subnet, namely 10.11.97.0/24. I'm going to write a pull request to make Gatekeeper refuse similar configurations, but you don't need to wait on this change, just change your configuration.

As a side note, your diagram doesn't include a Grantor server. You'll need one to make Gatekeeper work. Moreover, you'll need a router between the Gatekeeper and Grantor servers as well. You likely can use one of the routers already in your infrastructure for that purpose.

**Comment by shirley04** [comment]
(1).  I changed the net configuration and network  topology .  I also did testing as follow:
       vm (10.11.98.0/24) used pktgen to send  paket to  kni_front successfully
       vm (10.11.98.0/24) used pktgen to send  paket to  kni_back unsuccessfully
       vm(10.11.98.11) can ping kni_front of gatekeeper successfully
       vm(10.11.98.11) can not  ping kni_back of gatekeeper, and it interupt the running gatekeeper, report error :assert "eth_cache != NULL" failed


vi lua/net.lua
        local front_ports = {"enp98s0f1"}
        local front_ips  = {"10.11.98.12/24", "2001:db8:1::1/48"}
        

        local back_ports = {"enp98s0f0"}
        local back_ips  = {"10.11.99.12/24", "2001:db8:2::1/48"}

_________________________________________________________________________________

 (2). I installed one Grantor server, front_ips=10.11.97.22 
       but report error:
       GATEKEEPER GT: /usr/share/lua/5.1/gatekeeper/lpmlib.lua:34: Expected `struct in6_addr &' as first argument
       GATEKEEPER GT: Fail::ed to create new Lua state at lcore 3
       Device with port_id=0 already stopped




in addition, the gatekeeper has another interface configured 10.11.97.200, which is in the same subnet as Grantor server.

**Comment by AltraMayor** [comment]
> (2). I installed one Grantor server, front_ips=10.11.97.22
> but report error:
> ```
>        GATEKEEPER GT: /usr/share/lua/5.1/gatekeeper/lpmlib.lua:34: Expected `struct in6_addr &' as first argument
>        GATEKEEPER GT: Fail::ed to create new Lua state at lcore 3
> ```

It seems that you're running an older version of Gatekeeper on your Grantor server since the version in our repository no longer produces the two log entries as they are listed above. Please keep track of the versions; otherwise, we're going to be lost.

> in addition, the gatekeeper has another interface configured 10.11.97.200, which is in the same subnet as Grantor server.

What do you mean here? Does your Gatekeeper server have a third interface with 10.11.97.200? If so, why do you need it?

**Comment by AltraMayor** [comment]
The recently merged pull request #521 rejects configurations whose front and back interfaces are in the same subnet, and pull request #522 addresses the assert `eth_cache != NULL` triggered by the experiments above.

If all problems described in this issue have been addressed, please close this issue.

**Comment by shirley04** [comment]
Now the  front and back interfaces are not in the same subnet, but when I  use other vm(10.11.98.11) ping the kni_back of gatekeeper,  The action will  interupt the running gatekeeper, report error: assert "eth_cache != NULL" failed
How to reslolve?
vi lua/net.lua
        local front_ports = {"enp98s0f1"}
        local front_ips  = {"10.11.98.12/24", "2001:db8:1::1/48"}
        

        local back_ports = {"enp98s0f0"}
        local back_ips  = {"10.11.99.12/24", "2001:db8:2::1/48"}

**Comment by AltraMayor** [comment]
Are you running the latest version on the repository and still getting `assert "eth_cache != NULL" failed`? If so, can you obtain the line of code? It must be another assert since pull request #522 solved the assert you've reported above.
