### ISSUE TITLE
Gatekeeper Compatible with DPDK 21.05?

### ISSUE THREAD

**Issue by psanders240** [AltraMayor/gatekeeper#541]
Hello,

I've been looking around the Gatekeeper docs, but I can't find where it states the recommended DPDK version. I am using 21.05 and having some compilation issues. I just want to rule out DPDK as the issue.

Thanks,
Pete

**Comment by AltraMayor** [comment]
Hi @psanders240,

The DPDK that comes with Gatekeeper includes patches that are not available upstream. So one needs to install that DPDK to run Gatekeeper. The next release of Gatekeeper, version 1.1, will update Gatekeeper's DPDK to the LTS version 20.11.1.

We've been gradually removing the dependency on these patches, but we don't know when Gatekeeper will be able to work with a mailine version of DPDK. You find more information about compiling the packages in the [`README.md`](https://github.com/AltraMayor/gatekeeper/blob/master/README.md).

Also notice that you may find some header issues if you are not running Ubuntu 20.04 LTS. Until version 1.1 is out, Ubuntu 20.04 LTS is the recommended platform.

**Comment by psanders240** [comment]
Hi, 

I'm with a company called Napatech, and we make SmartNICs with flow management functionality. We currently use our own patched DPDK library based on standard DPDK for DPDK based applications wanting to get packets from our SmartNIC. I am assuming that this won't work with Gatekeeper unless we integrate your DPDK patches into our library? We are also working on a native DPDK driver which will support all applicable DPDK calls.

Would it make more sense to integrate Gatekeeper with a Napatech SmartNIC when both Gatekeeper and Napatech can work with standard DPDK? 

Thanks,
Pete
