### ISSUE TITLE
Failed to initialize front interface on AWS EC2

### ISSUE THREAD

**Issue by steven20220000** [AltraMayor/gatekeeper#544]
ExecStart=/usr/sbin/gatekeeper $DPDK_ARGS -- $GATEKEEPER_ARGS (code=exited, status=255/EXCEPTION) 
gatekeeper.service: Main process exited, code=exited, status=255/EXCEPTION
 
/usr/share/lua/5.1/gatekeeper/staticlib.lua:530: Failed to initilialize front interface

AWS ec2 m4.10xlarge ubtun20.04  kernel5.4.0-1071-aws

net.lua:
 local front_ports = {"ens3"}
 local front_ips  = {"172.31.5.139"}

if_map.lua:
return {
	["ens3"] = "00:03.0",
	["ens4"] = "00:04.0",
}

But i get error when i try to compile from source:
linux/kni/kni_net.c:737:20: error: initialization of ‘void (*)(struct net_device *, unsigned int)’ from incompatible pointer type ‘void (*)(struct net_device *)’ [-Werror=incompatible-pointer-types]
  737 |  .ndo_tx_timeout = kni_net_tx_timeout,

**Comment by steven20220000** [comment]
@AltraMayor 
no more helpful info

**Comment by AltraMayor** [comment]
Hi @steven20220000,

You have two hard nuts on hand.

First hard nut. The kernel of your instance has patches from future kernels. The signature of `ndo_tx_timeout` in a 5.4 kernel is `void
(*)(struct net_device *dev)`. This signature was changed in commit `0290bd291cc0e`; you can find this information using `git blame include/linux/netdevice.h` on Linus' repository of the kernel. And this commit is included in the following releases:
```
$ git tag --contains 0290bd291cc0e | grep -v rc
v5.10
v5.11
v5.12
v5.13
v5.14
v5.15
v5.16
v5.17
v5.6
v5.7
v5.8
v5.9
```
As you can see above, the earliest that the interface of `ndo_tx_timeout` changed was in release v5.6. So you have a patched kernel that is not compatible with the binary interface of a 5.4 kernel. You'll either need (1) to try another kernel if available, (2) to wait for Gatekeeper v1.1, or (3) to abandon AWS.

(1) would be the easiest path if possible. For (2), we don't know when Gatekeeper v1.1 will be out, but you can keep an eye on our progress [here](https://github.com/AltraMayor/gatekeeper/milestone/10). (3) may be your best option; see below the why.

Second hard nut. We've tested Gatekeeper on AWS, and our experience was not positive. You can find most of the problems we've faced in Section "2.4.2.2 AWS EC2" of [Cody's PhD thesis](https://github.com/AltraMayor/gatekeeper/wiki/docs/Cody-Thesis.pdf). The link to Cody's PhD thesis and other publications are listed in our [Publications page](https://github.com/AltraMayor/gatekeeper/wiki/Publications) of [our wiki](https://github.com/AltraMayor/gatekeeper/wiki).

**Comment by steven20220000** [comment]
Thank you. I will try another kernel on AWS ec2

**Comment by steven20220000** [comment]
@AltraMayor 
I tried another kernel and successfully compile. Binding NIC is OK, but failed to start gatekeeper.  The info is:

**root@ip-172-31-4-140:~/gatekeeper# ./build/gatekeeper 
EAL: Detected 40 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:10ed net_ixgbe_vf
EAL: PCI device 0000:00:04.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:10ed net_ixgbe_vf
EAL: See files in . for further log
root@ip-172-31-4-140:~/gatekeeper#** 
**GATEKEEPER: main: cycles/second = 2400238222, cycles/millisecond = 2400238, picosec/cycle = 416
GATEKEEPER: config: ./lua/gatekeeper/staticlib.lua:530: Failed to initilialize front interface
GATEKEEPER: main: failed to configure Gatekeeper
**

**Comment by AltraMayor** [comment]
Hi @steven20220000,

Once you compiled everything with the new kernel, did you review the content of `setup.sh` to make sure that the module is available to the new kernel? The essential part of `setup.sh` here would be the lines between `# Install kernel modules.` and `# Setup LuaJIT.` You may have missed this step if you just installed the new kernel and compiled DPDK directly.

Have you set up hugepages on this machine?
