### ISSUE TITLE
Gatekeeper Install

### ISSUE THREAD

**Issue by Pui142** [AltraMayor/gatekeeper#546]
Hello!

How this exactly work?
I successfully install gatekeeper.

But what exactly are back ports and back ips?
And what is grantor server?
Like i have 2 machine
One machine need to be grantor server and the another one Gatekeeper server?

Thanks

**Comment by AltraMayor** [comment]
> How this exactly work? And what is grantor server?

Check out our NANOG 82 presentation; links to the video and slides are available on our [Publications](https://github.com/AltraMayor/gatekeeper/wiki/Publications) page.

> But what exactly are back ports and back ips?

A Gatekeeper server has two ports. The front port receives the incoming traffic, which potentially includes DDoS attacks. The back port deals with traffic from the protected network. You find more at the FAQ question [Why do Gatekeeper servers need two network interfaces?](https://github.com/AltraMayor/gatekeeper/wiki/FAQ#Why_do_Gatekeeper_servers_need_two_network_interfaces). The page [Tips for Deployments](https://github.com/AltraMayor/gatekeeper/wiki/Tips-for-Deployments) may clarify this information with a fleshed-out example.

> Like i have 2 machine One machine need to be grantor server and the another one Gatekeeper server?

Yes, that's correct.

**Comment by Pui142** [comment]
Hello, @AltraMayor 

Any idea why i get this error when i try to start gatekeeper?
![image](https://user-images.githubusercontent.com/103855220/165572974-46bb2780-6912-4875-85d5-0a705b22f2ff.png)
![image](https://user-images.githubusercontent.com/103855220/165573256-d0f6bc7e-b173-441d-bd3f-35151d1ac668.png)

The error come from cps.lua when i try to set to use the correct path

**Comment by Pui142** [comment]
Hello, @AltraMayor 

When i try to start gatekeeper i get this error from DYN Configuration

![image](https://user-images.githubusercontent.com/103855220/165639703-e39df275-46fc-4fe4-a039-c3e04f49f9c3.png)

**Comment by AltraMayor** [comment]
Check variable `server_path` in your file `./lua/dyn_cfg.lua`. Does the path before the filename exist?

**Comment by Pui142** [comment]
Hi,

No, he doesn't exist.

In **local server_path = "/var/run/gatekeeper/dyn_cfg.socket"** the folder _gatekeeper_  in /var/run/ he doesn't exist

**Comment by AltraMayor** [comment]
Create it: `mkdir -p /var/run/gatekeeper`
