### ISSUE TITLE
attempt to call field 'str_to_prefix' ‘IPV4’‘IPV6’

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#554]
Example lua script policy.lua , calling str_to_prefix, policylib.c.IPV4, policylib.c.IPV6, without constructing str_to_prefix, IPV4, IPV6
attempt to call field 'str_to_prefix' 
The script example calls the C function, the construction method is not perfect, and the call is written at will, resulting in failure to run, whether there is a complete LPM strategy and policy strategy With the functions of adding, deleting, modifying, and viewing

**Comment by AltraMayor** [comment]
I've understood that you are looking for an easier way to dynamically maintain LPM tables. You find an example of how to do it at section [Updating LPM tables with with drib and gtctl](https://github.com/AltraMayor/gatekeeper/wiki/Tips-for-Deployments#updating-lpm-tables-with-with-drib-and-gtctl) of the wiki page [Tips for Deployments](https://github.com/AltraMayor/gatekeeper/wiki/Tips-for-Deployments).
