### ISSUE TITLE
Patch relevant BGP speaker(s)

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#56]
Issue #27 makes it so that the BGP speakers that use the KNI can edit the routing table of GK blocks.

The problem is that this routing table is duplicated: once in the kernel and once in Gatekeeper. Instead, it would be better to have the BGP speaker directly communicate with the CPS block using Netlink.

We need to find which BGP speaker(s) are relevant for our deployment(s), and patch them to include this functionality. The BGP speaker Bird (http://bird.network.cz/) is a strong candidate to be patched given its popularity. Another positive factor is that they have documentation for developers:

http://bird.network.cz/?get_doc&f=prog.html

**Comment by cjdoucette** [comment]
When complete, this feature should remove the `TODO` in `cps/kni.c:route_event_sock_open()`.

**Comment by AltraMayor** [comment]
We are sticking with Bird for the first deployments.

**Comment by cjdoucette** [comment]
With the latest pull request, we have all BIRD functionality but we get the following messages when running BIRD:

```
bird: Started
bird: KRT: Received route 10.0.1.0/24 with strange next-hop 0.0.0.0
bird: KRT: Received route 10.0.2.0/24 with strange next-hop 0.0.0.0
bird: Netlink: Address family not supported by protocol
```

The route error message happens when we report neighbor routes with a next hop of 0.0.0.0, because this code gets executed in BIRD:

https://github.com/cjdoucette/bird/blob/gatekeeper/sysdep/linux/netlink.c#L1667-L1675

The `neigh_find()` function can't find a neighbor 0.0.0.0:

https://github.com/cjdoucette/bird/blob/master/nest/neighbor.c#L141-L159

I'm not sure if we can safely ignore this.

The second error occurs because BIRD tries to get routes for `AF_MPLS`, which Gatekeeper does not support and therefore notifies the daemon.

**Comment by AltraMayor** [comment]
Based on the code of BIRD that you highlighted, we must not include `RTA_GATEWAY` while sending neighbor routes to Bird.

BIRD is compiled to support MPLS depending on the kernel (see `#ifdef HAVE_MPLS_KERNEL` in the code). I think we should avoid that warning supporting MPLS by just returning an empty list (i.e. just the DONE message).

We should open a new issue in the First Deployment milestone to deal with these two errors.

**Comment by AltraMayor** [comment]
By the way, Gatekeeper has routes of the type `GK_DROP`, which should be reported to BIRD as `RTN_BLACKHOLE`. Add this too to the new issue.
