### ISSUE TITLE
BPF index grouping

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#565]
How many INDEX can be configured for each BPF, assigned to different business groups, such as granted BPF, I want to set the parameters of different groups
tx_rate_kib_sec
next_renewal_ms
renewal_step_ms
it allows me to set up to how many groups

**Comment by AltraMayor** [comment]
The GK block, whose configuration is in [file `lua/gk.lua`](https://github.com/AltraMayor/gatekeeper/blob/e52bbf2340ec196e8de12fb5b4287c48434c663b/lua/gk.lua), supports 256 BPF programs; the indexes of these BPF programs go from 0 to 255. Although 256 is a "small" number, we are not aware of anyone that got close to half of this limit in production. If this happens, we'll work to lift this limit.

The reason deployments don't need lots of BPF programs is that these programs have parameters, so they can be customized to the flow they are associated with. A Lua policy associates each flow to one of the BPF programs available at the GK block **and** the parameters for the BPF program. Given this flexibility, you can have as many business groups as you need.
