### ISSUE TITLE
Running tcpdump on kni interfaces brings BGP sessions down

### ISSUE THREAD

**Issue by andrenth** [AltraMayor/gatekeeper#570]
When I run tcpdump on one of the KNI interfaces used by Gatekeeper, it immediately brings down BGP sessions running on the respective interfaces (the connection state in Bird changes to "Neighbor lost").

There are no correlated errors that I could find. `ifconfig` and `ethtool` outputs don't change during the tcpdump execution. There are no Gatekeeper logs, and the only kernel messages are the ones indicating the interfaces entered or left promiscuous mode.

Once tcpdump is stopped, the session is restablished via BGP's retry mechanisms.

**Comment by AltraMayor** [comment]
Once this issue is taken back again, verify if pull request #623 solved this issue by ignoring requests to set promiscuous mode.

**Comment by AltraMayor** [comment]
Pull request #678 replaced DPDK's KNI library with virtio-user, and virtio-user does not have this problem.
