### ISSUE TITLE
/lua/gk.lua:92: 'struct gk_config' has no member named 'fib_dump_batch_size'

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#581]
Gatekeeper 1.1.0 deployment The following error occurs, the GK server cannot be initialized
/lua/gk.lua:92: 'struct gk_config' has no member named 'fib_dump_batch_size'

**Comment by AltraMayor** [comment]
It seems that you have mixed files from v1.0.0 and v1.1.0 somehow. The field `fib_dump_batch_size` is new in v1.1.0.

**Comment by ShawnLeung87** [comment]
This has been resolved, this is because the lib files in /usr/local/share/lua/5.1/gatekeeper are read, these files are version 1.0.0.
lpm failed to initialize the problem, gt_lpm_ud expected, got number error in version 1.1.0 #580, I have completely cleared /usr/local/share/lua/5.1/gatekeeper on the GT server, this problem should be the same, I don't know yet What is the problem? This problem may be caused by the unsuccessful loading of lpmlib

**Comment by AltraMayor** [comment]
Issue #580 was solved, so this thread is also solved.
