### ISSUE TITLE
Fix prefix security hole vulnerability

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#60]
We need to make sure that prefixes for existing drop and Grantor entries can only be superseded by new prefixes for drop or Grantor entries. 

For example, assume there's a prefix 10.1.1.0/24 that leads to a gateway and the prefix being added to a grantor is 10.1/16. The gateway entry would be a security hole.

The solution is to extend RTE LPM table to have an iterator over its entries. The iterator should require a prefix as a parameter and should list all entries as long as the given prefix (or longer). To list all entries, the given prefix would have length zero.

This feature should remove the relevant `TODO` in `gk/fib.c`.

**Comment by AltraMayor** [comment]
Pull request #88 addressed this issue.
