### ISSUE TITLE
Deployment on Cent OS 7x

### ISSUE THREAD

**Issue by Binary-Vanguard-12138** [AltraMayor/gatekeeper#607]
Can we compile and install gatekeeper on Cent OS?
I have checked the all contents in repository and found that it aims to be installed on Ubuntu.
But in the production, we need to use it on CentOS.

**Comment by AltraMayor** [comment]
I think it is possible to compile and install Gatekeeper on CentOS. But given that our team is not familiar with that distro, you have to figure out the details on your own. If you do, please post online how you did; this could help someone else. Although issue #499 is related to two different versions of Ubuntu, it gives you a clue about the kind of problems to expect.

Gatekeeper version 1.0 is still the stable version. Version 1.1 should be out before the end of this year. And version 1.2 sometime next year. Version 1.2 will work with stock DPDK, lowering the effort to get Gatekeeper running on other distros.

If you can open an exception to run Gatekeeper in production on Ubuntu for about one year, you'll have an easier time making it run on CentOS next year.
