### ISSUE TITLE
BPF rejects large package problem

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#617]
When normal service data packets enter BPF,
large packets cannot pass through
I tested both gatekeeper v 1.1 and v1.0 BPF, the large packet cannot pass through the problem, even if I adjust the tx_rate_kib_sec to the maximum, this problem still exists. GK-GT network I set up to support mtu 2048. When entering BPF, you can make http get requests, similar to ssl post requests will be rejected, and ssh will also be rejected. The ip segment does not enter FWD_GRANTOR, and the data packets can pass normally.
1、I have used decision_granted_nobpf and it also fails to grant large packets.
(gatekeeper v1.0 )
flow status
GATEKEEPER: flow: gk: log the flow state [state: GK_GRANTED (1), flow hash value: 97177530, expire_at: 283af420bb8c8, budget_renew_at: 28247676bbcf4, tx_rate_kib_cycle: 40444000, budget_byte: 9a4817a16, send_next_renewal_at: 282d5d7949d18, renewal_step_cycle: 1cfd1fdc8, grantor_ip: 10.0.2.11] in the flow table at print_flow_state with lcore 5 for the flow with IP source address 20.20.20.90, and destination address 30.30.30.30
 (gatekeeper v1.1)
[2022-10-18 11:11:04] GK/7: Flow (src: 20.20.20.20, dst: 30.30.30.30) at index 15: [state: GK_GRANTED (1), flow_hash_value: 0x74648fb, expire_at: 0x24a5dbd3a1284, budget_renew_at: 0x24a42f5e2b45d, tx_rate_kib_cycle: 40444, budget_byte: 41413142, send_next_renewal_at: 0x24aca72ea4830, renewal_step_cycle: 0x1cfd40168, grantor_ip: 10.0.2.11]
2、I have used  decision_grantedv2 ，fails to grant large packets.
（gatekeeper v1.0 ）
GATEKEEPER: flow: gk: log the flow state [state: GK_BPF (3), flow hash value: 97177530, expire_at: 0x28433c4d991e6, program_index=2, cookie=7025def211840200, 80cd7a00e0230600, 16fa35eb01000000, 00808f1800000000, a813107aa0840200, c8fdd1cf01000000, 0000000000000000, 0000000000000000, grantor_ip: 10.0.2.11] in the flow table at print_flow_state with lcore 5 for the flow with IP source address 20.20.20.90, and destination address 30.30.30.30
     (gatekeeper v1.1)
GK/7: Flow (src: 20.20.20.90, dst: 30.30.30.30) at index 4: [state: GK_BPF (3), flow_hash_value: 0x74648fb, expire_at: 0x2414294f1da28, program_index=2, cookie=ee72d1c220410200, 701f000092010000, 2cb47d0000000000, 0048060000000000, 82dfa14aaf410200, 6801d4cf01000000, 0000000000000000, 0000000000000000, grantor_ip: 10.0.2.11]
3、I have used decision_declined and can successfully reject ip packets through.
Both v1.1 and v1.0 are OK
4、Remove FWD_GRANTOR, can ssh.
1）30.30.30.0/24 is not in FWD_GRANTOR
![image](https://user-images.githubusercontent.com/104405912/196403934-f59f1111-1c7a-4be6-b02a-59b87e8a5f03.png)

2）30.30.30.0/24 is  in FWD_GRANTOR.
![image](https://user-images.githubusercontent.com/104405912/196404014-680f07ee-e9af-4937-ab17-34c677ac7678.png)

HTTP GET request
![image](https://user-images.githubusercontent.com/104405912/196404055-dd014b03-3507-477a-ab72-89163b77c7ed.png)

5、my network topology.
![image](https://user-images.githubusercontent.com/104405912/196404095-398e1082-f204-4440-93f5-fedb1542026e.png)

6、From the test results, the data packets have been successfully entered into the BPF for analysis and actions. The problem is that when the TCP request and the src ip secondary ack data packets are too large, they will be rejected.How can i solve this problem?

**Comment by AltraMayor** [comment]
At case "4、Remove FWD_GRANTOR, can ssh." how do packets from client to server get to the server without that route?

Could you use option `-s` of `ping` to find out which exact size the packet is dropped?

What Is the value of the parameter `back_ips` in `net.lua` of the Gatekeeper server and the parameter `front_ips` in `net.lua` of the Grantor server? If they are on the same LAN, you'll want to swap the "back-end switch" with "the GW route", so there's at least one router between the Gatekeeper and Grantor server. The technical reason for this is discussed in issue #267.

Is it possible to capture packets on the "GW route"? Inspecting these packets with Wireshark may have some clue to the problem.

**Comment by ShawnLeung87** [comment]
gatekeeper back port mtu 2048
gw route port mtu 2048
grantor front port mtu 2048
This configuration can solve the problem that packets larger than 1453 cannot pass through.
