### ISSUE TITLE
Redirect IPv6 packets received in error

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#63]
The IPv6 ntuple filter is unable to verify the destination IP address of the packet, so it's possible that Gatekeeper could receive a packet that is not destined for it. In that case, we should redirect the packet.

This has only been marked as a `TODO` for the GT-GK Unit (the back interface), since the front interface (the GK block) already forwards IPv6 traffic as needed.

This feature should remove the relevant `TODO` in `ggu/main.c`.

**Comment by AltraMayor** [comment]
The tag `TODO` was changed to `XXX` since this issue is currently in the milestone `Advanced features`.
