### ISSUE TITLE
Use l_lpm_lookup to query the policy id, and the maximum integer value is 2147483647. Is it normal?

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#632]
In the current program version, lpm is replaced by the fib method to query the policy id. When the prefix does not exist, the maximum integer value 2147483647 will be returned. This situation will not occur in the old version of the lpm method

**Comment by AltraMayor** [comment]
Thank you for reporting this bug.

Could you test pull request #633 to make sure it solves this issue?

**Comment by ShawnLeung87** [comment]
The return value is already normal, the same as the return value of the previous version

> 感谢您报告此错误。
> 
> 您可以测试拉取请求#633以确保它解决了这个问题吗？
