### ISSUE TITLE
About BPF, the calculation of budget1_byte

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#643]
Whether the budget1_byte of state in BPF is reduced cumulatively or re-decreased every time pkt_len. For example
budget1_byte=1024
Does it decrease cyclically, or re-start from 1024-pkt_len each time？
In a cap_expire_sec time, if a flow is recalculated every time, then every time I launch an attack, it will be smaller than budget1_byte, won’t it never be possible to trigger rejection?

**Comment by ShawnLeung87** [comment]
Like this, can I set an interval time, count the number of occurrences of the corresponding package, and reject the flow after the number reaches?

**Comment by AltraMayor** [comment]
> Like this, can I set an interval time, count the number of occurrences of the corresponding package, and reject the flow after the number reaches?

Yes, you can implement a BPF to do exactly that.

**Comment by ShawnLeung87** [comment]
When the flow reaches the next request to renew, package rejection occurs, about 50 packages. Which bpf parameter affects this. Is this renewal_step_ms?

**Comment by AltraMayor** [comment]
There's not much information on what you're testing to answer this question. Which BPF are you testing? What're the parameters? What's the expiration of the policy decision? How are you measuring that packet loss? What's the condition of the network during the test (e.g. attacks going on, network capacity vs traffic volume, packet drops on the path, etc.)? How are you producing the flow being measured? How have you narrowed down the issue to the renewal of the policy decision?

**Comment by ShawnLeung87** [comment]
I have solved this problem because the wrong parameters of the bpf call I wrote were caused.
Can't BPF state add more parameters? We need more parameters here to judge whether the number of tcp flags in the tcp three-way handshake is normal, so as to filter the flow. This type of judgment is mainly used in tcp slow attack. Because the original web bpf or tcp-srv bpf of our test project does not satisfy the defense against tcp slow attacks. Even if the second-level packet speed is used, slow tcp attacks cannot be blocked. Slow attacks are closer to the normal service access frequency. Using packet rate limiting has no effect. Packet speed limit is mainly satisfied in fast flood.

**Comment by AltraMayor** [comment]
As I have explained [here](https://github.com/AltraMayor/gatekeeper/issues/642#issuecomment-1587442686), adding more parameters to the BPFs associated with the flows may not be cheap to do.

If you had any amount of memory desired, what would you implement in the BPF you want? I'm asking because once I understand what you're trying to code, I may be able to guide you to get there through a different path.

You mention "Slow attacks are closer to the normal service access frequency." How can you differentiate these flows from regular flows? Have you tried threat intelligence such as [the IP Reputation Feed from Team Cymru](https://www.team-cymru.com/ip-address-reputation-check)?

**Comment by ShawnLeung87** [comment]
Currently I have three gatekeepers, each with 1.5T capacity ddr4, is it possible to increase the BPF status parameter？
struct gk_bpf_cookie {
uint64_t mem[8];
};

**Comment by AltraMayor** [comment]
1.5TB is certainly enough capacity to experiment with a larger BPF cookie. I wrote [this patch](https://github.com/AltraMayor/gatekeeper/files/11882039/cookie16.txt) to show the minimum amount of changes that you need to make to compile Gatekeeper with `uint64_t mem[16];`.

You can try larger cookies as well. I recommend using a multiple of 8 in `uint64_t mem[X];` to keep alignment with the cache lines of the processors.

Good luck!

**Comment by ShawnLeung87** [comment]
For this patch, should both gatekeeper and grantor be updated?

**Comment by AltraMayor** [comment]
Yes.
