### ISSUE TITLE
Add support for dumping GK FIB entries

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#65]
It might be useful to dynamically dump the GK FIB tables for debugging purposes. This feature should add this ability as well as the component of the dynamic configuration block that would enable it.

This feature should remove the `TODO` in `include/gatekeeper_fib.h`.

**Comment by mengxiang0811** [comment]
This also relates to issue #60, since it needs to first iterate over the LPM table to get the _<IP prefix, nexthop>_ tuple, and then use the _nexthop_ field to get the FIB entry for that prefix.
