### ISSUE TITLE
About the gateway packet problem

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#652]
GK_BPF_PKT_RET_DECLINE The rejected package is blocked in the front interface of the gateway. But the back interface does not see the reject packet. What is the reason for this?

**Comment by ShawnLeung87** [comment]
Is it because I use update_grantor_entry_lb load balancing problem? Do all grantor traffic go to the gateway front interface and then to the grantor?

**Comment by AltraMayor** [comment]
> GK_BPF_PKT_RET_DECLINE The rejected package is blocked in the front interface of the gateway. But the back interface does not see the reject packet. What is the reason for this?

When a BPF associated with a flow returns `GK_BPF_PKT_RET_DECLINE`, the Gatekeeper server drops that packet. Can you describe the need you have that requires you to forward a blocked packet?

> Is it because I use update_grantor_entry_lb load balancing problem?

I don't know to which problem you are referring here.

> Do all grantor traffic go to the gateway front interface and then to the grantor?

All incoming traffic should come into the front interfaces of your Gatekeeper servers. Gatekeeper servers forward to Grant servers only packets of flows that need a policy decision, or that BPFs ask for the help of Grantor servers to deliver them to the destinations; the latter is typically used in production for diagnosis purposes only.

**Comment by ShawnLeung87** [comment]
This problem is because of my network architecture problem. Grantor, gatekeeper, and Gateway are on the same switch. The communication between gatekeeper and grantor is not Layer 2 communication, they need to be forwarded through gateway. So we will see a lot of traffic on the gateway interface, but not forwarded to the downstream server. Because the grantor has enabled policy return false, the first packet of the flow will be discarded. The problem I have now is that the first packet discarding pressure is placed on the grantor. How to improve the processing performance of the grantor? Are there any good suggestions?

**Comment by AltraMayor** [comment]
Grantor servers receive at most 5% of the bandwidth (see the SOL [parameter `req_bw_rate`](https://github.com/AltraMayor/gatekeeper/wiki/Functional-Block:-SOL#request-channel-bandwidth-rate) in `lua/sol.lua` for more information), and Grantor servers work in groups. So Grantor servers are typically not overloaded.

Notice that even if you set your Grantor servers to discard all first packets of flows in need of policy decisions, this does not change their load since Gatekeeper servers will still enforce the limit of 5% of the bandwidth. While improving your Lua policy would improve the performance of your Grantor servers, this is often not realistic since Lua policies are typically efficient already.

**Comment by ShawnLeung87** [comment]
Because flow is abused, usually only one packet is sent. Currently, I can only use grantor to discard the first packet to achieve filtering. Even if the blacklist is enabled to DECLINE packets, the final pressure is on the grantor. We have three gatekeepers and three grantors. When the total amount of small data packets (64 bytes) abused by the flow is greater than 2g, it is easy to cause data packets to be unreachable, or the bird bgp session reload in the gratekeeper.Is this a problem because req_bw_ratelua/sol.lua is 0.05? Our NIC is 40G.

**Comment by ShawnLeung87** [comment]
The 2G small data packet attack (64 bytes) cannot be filtered and intercepted by gatekeeper's BPF, because there is only one packet flow, which does not meet the BPF filtering rules, and can only be discarded by grantor. Here, the grantor needs to have relatively strong performance or load capacity.

**Comment by AltraMayor** [comment]
What does "the bird bgp session reload in the gatekeeper" mean? If you mean that the **front** BGP session between the router and your Gatekeeper server is being lost and reestablished, your problem may not be related to the Grantor servers.

How do you load balance your Gatekeeper servers at the router? Do you use ECMP? If so, did you set up your router to use **only** the source and destination IP addresses of the packets to spread the packets over your three Gatekeeper servers?
