### ISSUE TITLE
Is it possible to adjust flow_ht_size to exceed 1 billion flows?

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#657]
Is it possible to adjust flow_ht_size to exceed 1 billion flows?I try to adjust more than 1 billion flows, but the gatekeeper cannot start. Is there a limit in the code? According to the current 1 billion flows, only 256GB of memory is used, but I still have 3/4 of my 1.5TB of memory free. How to let the gatekeeper use the free memory?

**Comment by AltraMayor** [comment]
> Is it possible to adjust flow_ht_size to exceed 1 billion flows?I try to adjust more than 1 billion flows, but the gatekeeper cannot start.

No error message?

> Is there a limit in the code?

There's no explicit limit other than the bit-length of the variables that control the flow table.

> According to the current 1 billion flows, only 256GB of memory is used, but I still have 3/4 of my 1.5TB of memory free. How to let the gatekeeper use the free memory?

There's a chance you're facing a limitation of the memory allocator of DPDK (see more information at issue #455). You can increase that limit following what was done there. But you are better off adding more Gatekeeper servers to split that memory. The reason for that is (1) to contain the demand for policy decisions if a Gatekeeper server is lost, and (2) the extra resources that more Gatekeeper servers add do help under the worst conditions. Another reason for favoring more Gatekeeper servers than servers with more memory is that the latter setup is not as tested as the former, so you may run into other problems.

**Comment by ShawnLeung87** [comment]
flow_ht_size is greater than 260000000, the log error is as follows
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
[2023-08-28 14:16:00] Main/0: The GK block can't create flow entry table at lcore 6
[2023-08-28 14:16:05] Main/0: Failed to setup gk instances for GK block at lcore 6

**Comment by AltraMayor** [comment]
Those log entries confirm that you're facing a limitation of the memory allocator of DPDK.
