### ISSUE TITLE
Failed to run dynamic config block

### ISSUE THREAD

**Issue by bhattaraiakshaya** [AltraMayor/gatekeeper#658]
I believe the port is being used by some other process. 

```
Main/0: run_dynamic_config(): Failed to bind the server socket (/var/run/gatekeeper/dyn_cfg.socket), errno=2: No such file or directory
Main/0: config: ./lua/dyn_cfg.lua:51: Failed to run dynamic config block
Main/0: Failed to configure Gatekeeper
```

**Comment by AltraMayor** [comment]
Likely, Ubuntu's initialization scripts flushed `/var/run` after a reboot of the machine. This would not allow Gatekeeper to create the Unix socket `dyn_cfg.socket` at `/var/run/gatekeeper`. The solution is to run the last lines of `setup.sh` after a reboot.
```
$ tail -n4 setup.sh 

sudo mkdir -p /var/run/gatekeeper/
sudo chown -R $USER:$GROUPS /var/run/gatekeeper/
sudo chmod -R 700 /var/run/gatekeeper/
```
Given that you are compiling and running Gatekeeper from scratch, you're working in what could be called "development mode". "Production mode" would be employing the Debian packages available with stable releases or building and using your own Debian packages as described in the README.md file. In production mode, the starting script of Gatekeeper takes care of chores like having the folder `/var/run/gatekeeper` ready before Gatekeeper starts.

**Comment by arvindin** [comment]
It finally works, last trivial issue we see is (I believe now I have to link all up):

Main/0: net: querying port 0, and link is down
Main/0: net: querying port 0, and link is down
Main/0: net: querying port 0, and link is down
Main/0: net: querying port 0, and link is down
Main/0: net: querying port 0, and link is down
Main/0: net: querying port 0, and link is down
Main/0: net: querying port 0, and link is down
Main/0: net: giving up on port 0
Invalid port_id=0
Main/0: net: failed to start Gatekeeper network
Device with port_id=1 already stopped
Invalid port_id=1
