### ISSUE TITLE
i only have 1 and i cant use both on front and back

### ISSUE THREAD

**Issue by gabbelitoV2** [AltraMayor/gatekeeper#675]
i only have 1 and i cant use both on 

![image](https://github.com/AltraMayor/gatekeeper/assets/128819414/ecc18808-6f5e-4fe1-a3a3-9fdcf9df854e)
![image](https://github.com/AltraMayor/gatekeeper/assets/128819414/51ace410-29b6-4184-9864-8643fac5bac7)

**Comment by AltraMayor** [comment]
That's a design decision. See question [Why do Gatekeeper servers need two network interfaces?](https://github.com/AltraMayor/gatekeeper/wiki/FAQ#why-do-gatekeeper-servers-need-two-network-interfaces) in the [FAQ](https://github.com/AltraMayor/gatekeeper/wiki/FAQ).

**Comment by gabbelitoV2** [comment]
are there 2 internet cables you need then?

**Comment by AltraMayor** [comment]
You'll need a cable per port, so two ports require two cables. I'm not sure I understood your question.

For a step-by-step guide on setting up a testing environment, read the page [Tips for Deployments](https://github.com/AltraMayor/gatekeeper/wiki/Tips-for-Deployments) of [our wiki](https://github.com/AltraMayor/gatekeeper/wiki/).

**Comment by gabbelitoV2** [comment]
means if it is enough to have 1 cable in the computer

**Comment by AltraMayor** [comment]
No

**Comment by gabbelitoV2** [comment]
wouldn't it be possible with 1 internet cable?

**Comment by AltraMayor** [comment]
No
