### ISSUE TITLE
1.2 dev i40e scenario：bpf function in policylib.lua, if return is false, the tcp port is unreachable. But icmp is normal

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#681]
bpf function in policylib.lua, if return is false, the tcp port is unreachable. But icmp is normal.
But I can access it normally in 82599ES 10-Gigabit scenario
I tested the default function and it also had this problem.
For example  function decision_grantedv2_will_full_params()

My production environment is i40e scenario, if this problem cannot be solved. First packet discarding will not be possible.

**Comment by AltraMayor** [comment]
I understand that the "82599ES 10-Gigabit scenario" is your test environment, which differs from your production environment in hardware and configuration. We need more information to even guess if the problem you're reporting is hardware, configuration, or a bug in the development version of Gatekeeper. The easier way to move forward here is to modify your test environment to become closer to your production environment so your test environment can reproduce the problem. Once your test environment can reproduce the problem, you can collect flow state, capture packets, debug policy, etc., to track down what's going wrong.

**Comment by ShawnLeung87** [comment]
No error output. Only the corresponding network card appears in dmesg
Masking broken INTx support
vfio_ecap_init: hiding ecap 0x19@0x1d0
And check the flow status. The gatekeeper receives the policy normally.

**Comment by ShawnLeung87** [comment]
At present, I only locate the problem here. But I don’t know what causes rte_pktmbuf_free(m); and subsequent data packets cannot pass.
			/*
			 * Lookup the policy decision.
			 *
			 * The policy, which is defined by a Lua script,
			 * decides which capabilities to grant or decline,
			 * the maximum receiving rate of the granted
			 * capabilities, and when each decision expires.
			 */
			ret = lookup_policy_decision(
				&pkt_info, &policy, instance);
			if (ret < 0) {
				rte_pktmbuf_free(m);
				continue;
			}

			/*
			 * Add the policy decision to the notification
			 * packet to be sent to the GT-GK Unit.
			 */
			fill_notify_pkt(&policy, &pkt_info, instance, gt_conf);

			if (ret != 0) {
				ret = decap_and_fill_eth(m, gt_conf,
					&pkt_info, instance);
				if (ret < 0)
					rte_pktmbuf_free(m);
				else
					tx_bufs[num_tx++] = m;
			} else
                G_LOG(ERR, "policy return false!!!!\n");
				rte_pktmbuf_free(m);
		}

**Comment by ShawnLeung87** [comment]
I tried using decap_and_fill_eth and subsequent packets can pass

**Comment by ShawnLeung87** [comment]
I think it's strange that Gatekeeper has obtained a strategy, and the strategy is set_if_possible settings to TRUE. Successive packets should not go to Grantor. But Gatekeeper continued to send to Grantor. If Policy Return False, will always be RTE_PKTMBUF_FREE (M), release the cache, and then the subsequent data packet will be discarded.

**Comment by AltraMayor** [comment]
I don't follow your reasoning, but the line `G_LOG(ERR, "policy return false!!!!\n");` you added changed the meaning of the code well beyond having an extra log entry: the `else` clause has no braces, so the line `rte_pktmbuf_free(m);` is now being called in disregard of the `if` statement.

**Comment by ShawnLeung87** [comment]
It is currently not sure whether it is a compatibility issue with the kernel, dpdk, and xl710 driver. I need to take the time to verify. Currently we are temporarily using 1.2dev dpdk20.11 kni scenario for trial operation.

**Comment by AltraMayor** [comment]
Thanks for the update.
