### ISSUE TITLE
Verify UDP checksum in GT-GK Unit

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#69]
The GT-GK Unit should be verifying the UDP checksum for packets that it receives.

This feature should remove the relevant `XXX` in `ggu/main.c`.

**Comment by AltraMayor** [comment]
This issue could be addressed in issue #47.

**Comment by cjdoucette** [comment]
Students interested in the protecting GT-GK channel project could also show us their ability to understand the code and come up with a related solution by showing us how they would fix this issue.

**Comment by AltraMayor** [comment]
Given that we won't have the GT-GK channel protected in the first deployment, it's a good idea to implement this issue for the first deployment.
