### ISSUE TITLE
Ready for production

### ISSUE THREAD

**Issue by kleper** [AltraMayor/gatekeeper#700]
Do you know if a gatekeeper is currently used in production environments?

**Comment by AltraMayor** [comment]
Gatekeeper has been used in production even before the release of v1.0, as you can verify in [the third-party presentation](https://github.com/AltraMayor/gatekeeper/wiki/Publications#third-party-presentations) available on our Publications page. Moreover, all release candidates are deployed and tested in production before I release the corresponding stable version.
