### ISSUE TITLE
Dependencies : Python module elftools not found

### ISSUE THREAD

**Issue by hzc12321** [AltraMayor/gatekeeper#719]
While following the steps documented in readme.md to compile the source of v1.2.0 RC2, running `. setup.sh` presents the following error : 

No module named 'elftools'. This error fails the script.

It seems like a dependency for DPDK is missing.

I have also found a similar issue :
https://github.com/clearlinux/distribution/issues/1464

Relevant link : 
https://doc.dpdk.org/guides-22.03/rel_notes/release_21_02.html

I solved it by running `sudo apt install python3-pyelftools`

**Comment by AltraMayor** [comment]
Thank you for the information. Pull request #721 corrected the file README.md.
