### ISSUE TITLE
Randomize the secret key of the RSS hash

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#72]
The secret key of the RSS hash must be random in order to prevent hackers from knowing it.

This feature should remove the relevant `XXX` in `lib/net.c`.

**Comment by mengxiang0811** [comment]
We need to implement the secret key of RSS hash in a way that enables symmetric flow mapping, which produces the same RSS hash value even if the source and destination IPs and port numbers are reversed. In this way, packets belonging to the same flow can be processed by the same thread, thus it avoids locks. This is essential for scalable processing of packets.

**Comment by AltraMayor** [comment]
Hi @mengxiang0811,

Which use case are you considering? The packets that come back from destination servers don't need to look up the flow table, only the packets that go toward destination servers. Your suggestion is interesting, but I think we don't need it in Gatekeeper.

**Comment by mengxiang0811** [comment]
Hi @AltraMayor,

That's true. I am considering the scenario where the grantor severs may support complex policies generated by analyzing TCP-session in both directions. As this is common in network security systems such as stateful firewalls, intrusion detection systems.
