### ISSUE TITLE
Redirect DPDK log to file

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#76]
By default DPDK's logging system writes to the standard error device. Since Gatekeeper will run as a daemon, it would be more useful for all DPDK logs to be output to a file.

This should remove the relevant `XXX` tags in `lib/acl.c` and (if needed) in `main/main.c`.

**Comment by sudeepb02** [comment]
What would be the preferred method for creating the log file - using file handling in C or using any other DPDK function?
The `rte_log_register()` function takes string as input and returns an int but the documentation for the function listed [here](http://www.dpdk.org/doc/api/rte__log_8h.html#aa942f119a94f833f3138dd5d582e01b2) doesn't provide much information.

**Comment by AltraMayor** [comment]
The preferred method is the one that integrates best with DPDK. I recommend you to read some of DPDK's code related to logging as well as to investigate other projects that use DPDK to identify the options. You can present your founding with your opinion of them on this thread to get feedback before you start coding.

Remember that Gatekeeper is geared toward production, so having a way to name the log files and describing how to break up the log files (e.g. per hour, per minute) in the configuration of Gatekeeper is essential to complete this issue.
