### ISSUE TITLE
RTE env setting for setup script

### ISSUE THREAD

**Issue by Edwardhk** [AltraMayor/gatekeeper#83]
Hi community,

I have tried to follow the step on the markdown, it seems incorrect if we run as `$ ./setup.sh` as the `RTE_TARGET` and `RTE_SDK` are not set in current shell.

I have set the env succfessully using `$ . setup.sh`, it is supposed that running with `./` will export the environment variable to subshell, which is required later for the `make`.

The following is the error for the undefined env:
`Makefile:23: *** "Please define RTE_SDK environment variable.".  Stop.`

Therefore, it is suggested to edit the setup steps in the welcoming markdown file
from `$ ./setup.sh`
to `$ . setup.sh`

Many thanks,
Edward

**Comment by cjdoucette** [comment]
Hi @Edwardhk ,

I agree that this is an issue that needs fixing. Would you like to submit a pull request? It should be simple, and I would be happy to review and help if you need it.

**Comment by AltraMayor** [comment]
Pull request #99  addresses this issue.
