### ISSUE TITLE
Check for existing rte_kni kernel module

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#96]
If Gatekeeper shuts down unexpectedly, the kernel module rte_kni is left loaded. When Gatekeeper is restarted, if rte_kni is already loaded, Gatekeeper will fail.

On start, Gatekeeper should check whether rte_kni is already loaded so that it may continue without trying to load it and failing.

**Comment by AltraMayor** [comment]
Unloading may fail if there's another user for the kernel module, so this is not simple to add. But you bring a good point, and it'd be a good idea to get the version of the loaded module and print it out in the log for debug/diagnosis.

**Comment by mysticTot** [comment]
couldn't we go with some flag, same as `modprobe  --first-time  module_name` ?
This flag causes modprobe to fail if module is already loaded.

**Comment by mysticTot** [comment]
if this approach sounds good to everyone, then please assign this issue to me.
@cjdoucette @AltraMayor

**Comment by AltraMayor** [comment]
Hi @mysticTot,

That sounds fine. Good luck!

**Comment by AltraMayor** [comment]
GitHub seems to only allow me to assign contributors to an issue. So you'll need to get a pull request merged to be assigned to issues. But you can assume that this issue is yours.

**Comment by cjdoucette** [comment]
Just to clarify -- we don't use `modprobe` program directly -- we load the kernel module ourselves using `init_module()` in cps/kni.c. So you can use the same approach as the `--first-time` flag in `modprobe` (you'll have to look at the source), but the change is not as simple as just adding a flag to an invocation of `modprobe`.

**Comment by AltraMayor** [comment]
That seems to be the correct solution for me. But use `EEXIST` instead of `17` in the code.

Also, log the version of the module loaded as I suggest above. The version information will help with troubleshooting in production.

A simple way to test your code is to manually load the module before running Gatekeeper.
